
/*
 * Copyright (c) Alexander Kammerer 2015.
 *
 * All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 07:48:00 PM CEST 
//


package org.eclipse.smarthome.documentation.schemas.thing_description.v1_0;

import org.eclipse.smarthome.documentation.schemas.config_description.v1_0.ConfigDescription;
import org.eclipse.smarthome.documentation.schemas.config_description.v1_0.ConfigDescriptionRef;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for channelType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="channelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tags" type="{http://eclipse.org/smarthome/schemas/thing-description/v1.0.0}tags" minOccurs="0"/>
 *         &lt;element name="state" type="{http://eclipse.org/smarthome/schemas/thing-description/v1.0.0}state" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="config-description" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}configDescription"/>
 *           &lt;element name="config-description-ref" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}configDescriptionRef"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}idRestrictionPattern" />
 *       &lt;attribute name="advanced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="system" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "channelType", propOrder = {
        "itemType",
        "label",
        "description",
        "category",
        "tags",
        "state",
        "configDescription",
        "configDescriptionRef"
})
public class ChannelType {

    @XmlElement(name = "item-type", required = true)
    protected String itemType;
    @XmlElement(required = true)
    protected String label;
    protected String description;
    protected String category;
    protected Tags tags;
    protected State state;
    @XmlElement(name = "config-description")
    protected ConfigDescription configDescription;
    @XmlElement(name = "config-description-ref")
    protected ConfigDescriptionRef configDescriptionRef;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "advanced")
    protected Boolean advanced;
    @XmlAttribute(name = "system")
    protected Boolean system;

    /**
     * Gets the value of the itemType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * Sets the value of the itemType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setItemType(String value) {
        this.itemType = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the category property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the tags property.
     *
     * @return possible object is
     * {@link Tags }
     */
    public Tags getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     *
     * @param value allowed object is
     *              {@link Tags }
     */
    public void setTags(Tags value) {
        this.tags = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link State }
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link State }
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * Gets the value of the configDescription property.
     *
     * @return possible object is
     * {@link ConfigDescription }
     */
    public ConfigDescription getConfigDescription() {
        return configDescription;
    }

    /**
     * Sets the value of the configDescription property.
     *
     * @param value allowed object is
     *              {@link ConfigDescription }
     */
    public void setConfigDescription(ConfigDescription value) {
        this.configDescription = value;
    }

    /**
     * Gets the value of the configDescriptionRef property.
     *
     * @return possible object is
     * {@link ConfigDescriptionRef }
     */
    public ConfigDescriptionRef getConfigDescriptionRef() {
        return configDescriptionRef;
    }

    /**
     * Sets the value of the configDescriptionRef property.
     *
     * @param value allowed object is
     *              {@link ConfigDescriptionRef }
     */
    public void setConfigDescriptionRef(ConfigDescriptionRef value) {
        this.configDescriptionRef = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the advanced property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isAdvanced() {
        if (advanced == null) {
            return false;
        } else {
            return advanced;
        }
    }

    /**
     * Sets the value of the advanced property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setAdvanced(Boolean value) {
        this.advanced = value;
    }

    /**
     * Gets the value of the system property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isSystem() {
        if (system == null) {
            return false;
        } else {
            return system;
        }
    }

    /**
     * Sets the value of the system property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setSystem(Boolean value) {
        this.system = value;
    }

}
