
/*
 * Copyright (c) Alexander Kammerer 2015.
 *
 * All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 07:48:00 PM CEST 
//


package org.eclipse.smarthome.documentation.schemas.thing_description.v1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.eclipse.smarthome.schemas.thing_description.v1_0 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.eclipse.smarthome.schemas.thing_description.v1_0
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ThingDescriptions }
     */
    public ThingDescriptions createThingDescriptions() {
        return new ThingDescriptions();
    }

    /**
     * Create an instance of {@link ThingType }
     */
    public ThingType createThingType() {
        return new ThingType();
    }

    /**
     * Create an instance of {@link BridgeType }
     */
    public BridgeType createBridgeType() {
        return new BridgeType();
    }

    /**
     * Create an instance of {@link ChannelType }
     */
    public ChannelType createChannelType() {
        return new ChannelType();
    }

    /**
     * Create an instance of {@link ChannelGroupType }
     */
    public ChannelGroupType createChannelGroupType() {
        return new ChannelGroupType();
    }

    /**
     * Create an instance of {@link Tags }
     */
    public Tags createTags() {
        return new Tags();
    }

    /**
     * Create an instance of {@link State }
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Channels }
     */
    public Channels createChannels() {
        return new Channels();
    }

    /**
     * Create an instance of {@link Property }
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Properties }
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link ChannelGroup }
     */
    public ChannelGroup createChannelGroup() {
        return new ChannelGroup();
    }

    /**
     * Create an instance of {@link BridgeTypeRef }
     */
    public BridgeTypeRef createBridgeTypeRef() {
        return new BridgeTypeRef();
    }

    /**
     * Create an instance of {@link ChannelGroups }
     */
    public ChannelGroups createChannelGroups() {
        return new ChannelGroups();
    }

    /**
     * Create an instance of {@link SupportedBridgeTypeRefs }
     */
    public SupportedBridgeTypeRefs createSupportedBridgeTypeRefs() {
        return new SupportedBridgeTypeRefs();
    }

    /**
     * Create an instance of {@link Channel }
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link Option }
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Options }
     */
    public Options createOptions() {
        return new Options();
    }

}
