
/*
 * Copyright (c) Alexander Kammerer 2015.
 *
 * All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 07:48:00 PM CEST 
//


package org.eclipse.smarthome.documentation.schemas.thing_description.v1_0;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="thing-type" type="{http://eclipse.org/smarthome/schemas/thing-description/v1.0.0}thingType"/>
 *         &lt;element name="bridge-type" type="{http://eclipse.org/smarthome/schemas/thing-description/v1.0.0}bridgeType"/>
 *         &lt;element name="channel-type" type="{http://eclipse.org/smarthome/schemas/thing-description/v1.0.0}channelType"/>
 *         &lt;element name="channel-group-type" type="{http://eclipse.org/smarthome/schemas/thing-description/v1.0.0}channelGroupType"/>
 *       &lt;/choice>
 *       &lt;attribute name="bindingId" use="required" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}idRestrictionPattern" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "thingTypeOrBridgeTypeOrChannelType"
})
@XmlRootElement(name = "thing-descriptions", namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")
public class ThingDescriptions {

    @XmlElements({
            @XmlElement(name = "thing-type", type = ThingType.class),
            @XmlElement(name = "bridge-type", type = BridgeType.class),
            @XmlElement(name = "channel-type", type = ChannelType.class),
            @XmlElement(name = "channel-group-type", type = ChannelGroupType.class)
    })
    protected List<Object> thingTypeOrBridgeTypeOrChannelType;
    @XmlAttribute(name = "bindingId", required = true)
    protected String bindingId;

    /**
     * Gets the value of the thingTypeOrBridgeTypeOrChannelType property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thingTypeOrBridgeTypeOrChannelType property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThingTypeOrBridgeTypeOrChannelType().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ThingType }
     * {@link BridgeType }
     * {@link ChannelType }
     * {@link ChannelGroupType }
     */
    public List<Object> getThingTypeOrBridgeTypeOrChannelType() {
        if (thingTypeOrBridgeTypeOrChannelType == null) {
            thingTypeOrBridgeTypeOrChannelType = new ArrayList<Object>();
        }
        return this.thingTypeOrBridgeTypeOrChannelType;
    }

    /**
     * Gets the value of the bindingId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBindingId() {
        return bindingId;
    }

    /**
     * Sets the value of the bindingId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBindingId(String value) {
        this.bindingId = value;
    }

}
