sudo: required
dist: trusty

language: java
jdk: oraclejdk8
before_install: echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:PermSize=512m -XX:MaxPermSize=1g'" > ~/.mavenrc

#$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#$ mvn test -B

install: travis_wait 60 mvn clean install -B -V -q
