/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.rule.ui.contentassist

import org.eclipse.smarthome.model.rule.ui.contentassist.AbstractRulesProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RulesProposalProvider extends AbstractRulesProposalProvider {
}
