/**
 * Copyright (c) 2014,2018 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.smarthome.binding.bluetooth;

import java.util.HashMap;
import java.util.Map;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

/**
 * See https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers
 *
 * @author Kai Kreuzer - Initial contribution and API
 *
 */
@NonNullByDefault
public class BluetoothCompanyIdentifiers {

    private static final Map<Integer, String> cic = new HashMap<>();

    static {
        cic.put(0, "Ericsson Technology Licensing");
        cic.put(1, "Nokia Mobile Phones");
        cic.put(2, "Intel Corp.");
        cic.put(3, "IBM Corp.");
        cic.put(4, "Toshiba Corp.");
        cic.put(5, "3Com");
        cic.put(6, "Microsoft");
        cic.put(7, "Lucent");
        cic.put(8, "Motorola");
        cic.put(9, "Infineon Technologies AG");
        cic.put(10, "Cambridge Silicon Radio");
        cic.put(11, "Silicon Wave");
        cic.put(12, "Digianswer A/S");
        cic.put(13, "Texas Instruments Inc.");
        cic.put(14, "Parthus Technologies Inc.");
        cic.put(15, "Broadcom Corporation");
        cic.put(16, "Mitel Semiconductor");
        cic.put(17, "Widcomm, Inc.");
        cic.put(18, "Zeevo, Inc.");
        cic.put(19, "Atmel Corporation");
        cic.put(20, "Mitsubishi Electric Corporation");
        cic.put(21, "RTX Telecom A/S");
        cic.put(22, "KC Technology Inc.");
        cic.put(23, "Newlogic");
        cic.put(24, "Transilica, Inc.");
        cic.put(25, "Rohde & Schwarz GmbH & Co. KG");
        cic.put(26, "TTPCom Limited");
        cic.put(27, "Signia Technologies, Inc.");
        cic.put(28, "Conexant Systems Inc.");
        cic.put(29, "Qualcomm");
        cic.put(30, "Inventel");
        cic.put(31, "AVM Berlin");
        cic.put(32, "BandSpeed, Inc.");
        cic.put(33, "Mansella Ltd");
        cic.put(34, "NEC Corporation");
        cic.put(35, "WavePlus Technology Co., Ltd.");
        cic.put(36, "Alcatel");
        cic.put(37, "NXP Semiconductors (formerly Philips Semiconductors)");
        cic.put(38, "C Technologies");
        cic.put(39, "Open Interface");
        cic.put(40, "R F Micro Devices");
        cic.put(41, "Hitachi Ltd");
        cic.put(42, "Symbol Technologies, Inc.");
        cic.put(43, "Tenovis");
        cic.put(44, "Macronix International Co. Ltd.");
        cic.put(45, "GCT Semiconductor");
        cic.put(46, "Norwood Systems");
        cic.put(47, "MewTel Technology Inc.");
        cic.put(48, "ST Microelectronics");
        cic.put(49, "Synopsys, Inc.");
        cic.put(50, "Red-M (Communications) Ltd");
        cic.put(51, "Commil Ltd");
        cic.put(52, "Computer Access Technology Corporation (CATC)");
        cic.put(53, "Eclipse (HQ Espana) S.L.");
        cic.put(54, "Renesas Electronics Corporation");
        cic.put(55, "Mobilian Corporation");
        cic.put(56, "Terax");
        cic.put(57, "Integrated System Solution Corp.");
        cic.put(58, "Matsushita Electric Industrial Co., Ltd.");
        cic.put(59, "Gennum Corporation");
        cic.put(60, "BlackBerry Limited (formerly Research In Motion)");
        cic.put(61, "IPextreme, Inc.");
        cic.put(62, "Systems and Chips, Inc");
        cic.put(63, "Bluetooth SIG, Inc");
        cic.put(64, "Seiko Epson Corporation");
        cic.put(65, "Integrated Silicon Solution Taiwan, Inc.");
        cic.put(66, "CONWISE Technology Corporation Ltd");
        cic.put(67, "PARROT AUTOMOTIVE SAS");
        cic.put(68, "Socket Mobile");
        cic.put(69, "Atheros Communications, Inc.");
        cic.put(70, "MediaTek, Inc.");
        cic.put(71, "Bluegiga");
        cic.put(72, "Marvell Technology Group Ltd.");
        cic.put(73, "3DSP Corporation");
        cic.put(74, "Accel Semiconductor Ltd.");
        cic.put(75, "Continental Automotive Systems");
        cic.put(76, "Apple, Inc.");
        cic.put(77, "Staccato Communications, Inc.");
        cic.put(78, "Avago Technologies");
        cic.put(79, "APT Ltd.");
        cic.put(80, "SiRF Technology, Inc.");
        cic.put(81, "Tzero Technologies, Inc.");
        cic.put(82, "J&M Corporation");
        cic.put(83, "Free2move AB");
        cic.put(84, "3DiJoy Corporation");
        cic.put(85, "Plantronics, Inc.");
        cic.put(86, "Sony Ericsson Mobile Communications");
        cic.put(87, "Harman International Industries, Inc.");
        cic.put(88, "Vizio, Inc.");
        cic.put(89, "Nordic Semiconductor ASA");
        cic.put(90, "EM Microelectronic-Marin SA");
        cic.put(91, "Ralink Technology Corporation");
        cic.put(92, "Belkin International, Inc.");
        cic.put(93, "Realtek Semiconductor Corporation");
        cic.put(94, "Stonestreet One, LLC");
        cic.put(95, "Wicentric, Inc.");
        cic.put(96, "RivieraWaves S.A.S");
        cic.put(97, "RDA Microelectronics");
        cic.put(98, "Gibson Guitars");
        cic.put(99, "MiCommand Inc.");
        cic.put(100, "Band XI International, LLC");
        cic.put(101, "Hewlett-Packard Company");
        cic.put(102, "9Solutions Oy");
        cic.put(103, "GN Netcom A/S");
        cic.put(104, "General Motors");
        cic.put(105, "A&D Engineering, Inc.");
        cic.put(106, "MindTree Ltd.");
        cic.put(107, "Polar Electro OY");
        cic.put(108, "Beautiful Enterprise Co., Ltd.");
        cic.put(109, "BriarTek, Inc");
        cic.put(110, "Summit Data Communications, Inc.");
        cic.put(111, "Sound ID");
        cic.put(112, "Monster, LLC");
        cic.put(113, "connectBlue AB");
        cic.put(114, "ShangHai Super Smart Electronics Co. Ltd.");
        cic.put(115, "Group Sense Ltd.");
        cic.put(116, "Zomm, LLC");
        cic.put(117, "Samsung Electronics Co. Ltd.");
        cic.put(118, "Creative Technology Ltd.");
        cic.put(119, "Laird Technologies");
        cic.put(120, "Nike, Inc.");
        cic.put(121, "lesswire AG");
        cic.put(122, "MStar Semiconductor, Inc.");
        cic.put(123, "Hanlynn Technologies");
        cic.put(124, "A & R Cambridge");
        cic.put(125, "Seers Technology Co., Ltd.");
        cic.put(126, "Sports Tracking Technologies Ltd.");
        cic.put(127, "Autonet Mobile");
        cic.put(128, "DeLorme Publishing Company, Inc.");
        cic.put(129, "WuXi Vimicro");
        cic.put(130, "Sennheiser Communications A/S");
        cic.put(131, "TimeKeeping Systems, Inc.");
        cic.put(132, "Ludus Helsinki Ltd.");
        cic.put(133, "BlueRadios, Inc.");
        cic.put(134, "Equinux AG");
        cic.put(135, "Garmin International, Inc.");
        cic.put(136, "Ecotest");
        cic.put(137, "GN ReSound A/S");
        cic.put(138, "Jawbone");
        cic.put(139, "Topcon Positioning Systems, LLC");
        cic.put(140, "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)");
        cic.put(141, "Zscan Software");
        cic.put(142, "Quintic Corp");
        cic.put(143, "Telit Wireless Solutions GmbH (formerly Stollmann E+V GmbH)");
        cic.put(144, "Funai Electric Co., Ltd.");
        cic.put(145, "Advanced PANMOBIL systems GmbH & Co. KG");
        cic.put(146, "ThinkOptics, Inc.");
        cic.put(147, "Universal Electronics, Inc.");
        cic.put(148, "Airoha Technology Corp.");
        cic.put(149, "NEC Lighting, Ltd.");
        cic.put(150, "ODM Technology, Inc.");
        cic.put(151, "ConnecteDevice Ltd.");
        cic.put(152, "zero1.tv GmbH");
        cic.put(153, "i.Tech Dynamic Global Distribution Ltd.");
        cic.put(154, "Alpwise");
        cic.put(155, "Jiangsu Toppower Automotive Electronics Co., Ltd.");
        cic.put(156, "Colorfy, Inc.");
        cic.put(157, "Geoforce Inc.");
        cic.put(158, "Bose Corporation");
        cic.put(159, "Suunto Oy");
        cic.put(160, "Kensington Computer Products Group");
        cic.put(161, "SR-Medizinelektronik");
        cic.put(162, "Vertu Corporation Limited");
        cic.put(163, "Meta Watch Ltd.");
        cic.put(164, "LINAK A/S");
        cic.put(165, "OTL Dynamics LLC");
        cic.put(166, "Panda Ocean Inc.");
        cic.put(167, "Visteon Corporation");
        cic.put(168, "ARP Devices Limited");
        cic.put(169, "Magneti Marelli S.p.A");
        cic.put(170, "CAEN RFID srl");
        cic.put(171, "Ingenieur-Systemgruppe Zahn GmbH");
        cic.put(172, "Green Throttle Games");
        cic.put(173, "Peter Systemtechnik GmbH");
        cic.put(174, "Omegawave Oy");
        cic.put(175, "Cinetix");
        cic.put(176, "Passif Semiconductor Corp");
        cic.put(177, "Saris Cycling Group, Inc");
        cic.put(178, "Bekey A/S");
        cic.put(179, "Clarinox Technologies Pty. Ltd.");
        cic.put(180, "BDE Technology Co., Ltd.");
        cic.put(181, "Swirl Networks");
        cic.put(182, "Meso international");
        cic.put(183, "TreLab Ltd");
        cic.put(184, "Qualcomm Innovation Center, Inc. (QuIC)");
        cic.put(185, "Johnson Controls, Inc.");
        cic.put(186, "Starkey Laboratories Inc.");
        cic.put(187, "S-Power Electronics Limited");
        cic.put(188, "Ace Sensor Inc");
        cic.put(189, "Aplix Corporation");
        cic.put(190, "AAMP of America");
        cic.put(191, "Stalmart Technology Limited");
        cic.put(192, "AMICCOM Electronics Corporation");
        cic.put(193, "Shenzhen Excelsecu Data Technology Co.,Ltd");
        cic.put(194, "Geneq Inc.");
        cic.put(195, "adidas AG");
        cic.put(196, "LG Electronics");
        cic.put(197, "Onset Computer Corporation");
        cic.put(198, "Selfly BV");
        cic.put(199, "Quuppa Oy.");
        cic.put(200, "GeLo Inc");
        cic.put(201, "Evluma");
        cic.put(202, "MC10");
        cic.put(203, "Binauric SE");
        cic.put(204, "Beats Electronics");
        cic.put(205, "Microchip Technology Inc.");
        cic.put(206, "Elgato Systems GmbH");
        cic.put(207, "ARCHOS SA");
        cic.put(208, "Dexcom, Inc.");
        cic.put(209, "Polar Electro Europe B.V.");
        cic.put(210, "Dialog Semiconductor B.V.");
        cic.put(211, "Taixingbang Technology (HK) Co,. LTD.");
        cic.put(212, "Kawantech");
        cic.put(213, "Austco Communication Systems");
        cic.put(214, "Timex Group USA, Inc.");
        cic.put(215, "Qualcomm Technologies, Inc.");
        cic.put(216, "Qualcomm Connected Experiences, Inc.");
        cic.put(217, "Voyetra Turtle Beach");
        cic.put(218, "txtr GmbH");
        cic.put(219, "Biosentronics");
        cic.put(220, "Procter & Gamble");
        cic.put(221, "Hosiden Corporation");
        cic.put(222, "Muzik LLC");
        cic.put(223, "Misfit Wearables Corp");
        cic.put(224, "Google");
        cic.put(225, "Danlers Ltd");
        cic.put(226, "Semilink Inc");
        cic.put(227, "inMusic Brands, Inc");
        cic.put(228, "L.S. Research Inc.");
        cic.put(229, "Eden Software Consultants Ltd.");
        cic.put(230, "Freshtemp");
        cic.put(231, "KS Technologies");
        cic.put(232, "ACTS Technologies");
        cic.put(233, "Vtrack Systems");
        cic.put(234, "Nielsen-Kellerman Company");
        cic.put(235, "Server Technology Inc.");
        cic.put(236, "BioResearch Associates");
        cic.put(237, "Jolly Logic, LLC");
        cic.put(238, "Above Average Outcomes, Inc.");
        cic.put(239, "Bitsplitters GmbH");
        cic.put(240, "PayPal, Inc.");
        cic.put(241, "Witron Technology Limited");
        cic.put(242, "Morse Project Inc.");
        cic.put(243, "Kent Displays Inc.");
        cic.put(244, "Nautilus Inc.");
        cic.put(245, "Smartifier Oy");
        cic.put(246, "Elcometer Limited");
        cic.put(247, "VSN Technologies, Inc.");
        cic.put(248, "AceUni Corp., Ltd.");
        cic.put(249, "StickNFind");
        cic.put(250, "Crystal Code AB");
        cic.put(251, "KOUKAAM a.s.");
        cic.put(252, "Delphi Corporation");
        cic.put(253, "ValenceTech Limited");
        cic.put(254, "Stanley Black and Decker");
        cic.put(255, "Typo Products, LLC");
        cic.put(256, "TomTom International BV");
        cic.put(257, "Fugoo, Inc.");
        cic.put(258, "Keiser Corporation");
        cic.put(259, "Bang & Olufsen A/S");
        cic.put(260, "PLUS Location Systems Pty Ltd");
        cic.put(261, "Ubiquitous Computing Technology Corporation");
        cic.put(262, "Innovative Yachtter Solutions");
        cic.put(263, "William Demant Holding A/S");
        cic.put(264, "Chicony Electronics Co., Ltd.");
        cic.put(265, "Atus BV");
        cic.put(266, "Codegate Ltd");
        cic.put(267, "ERi, Inc");
        cic.put(268, "Transducers Direct, LLC");
        cic.put(269, "Fujitsu Ten LImited");
        cic.put(270, "Audi AG");
        cic.put(271, "HiSilicon Technologies Col, Ltd.");
        cic.put(272, "Nippon Seiki Co., Ltd.");
        cic.put(273, "Steelseries ApS");
        cic.put(274, "Visybl Inc.");
        cic.put(275, "Openbrain Technologies, Co., Ltd.");
        cic.put(276, "Xensr");
        cic.put(277, "e.solutions");
        cic.put(278, "10AK Technologies");
        cic.put(279, "Wimoto Technologies Inc");
        cic.put(280, "Radius Networks, Inc.");
        cic.put(281, "Wize Technology Co., Ltd.");
        cic.put(282, "Qualcomm Labs, Inc.");
        cic.put(283, "Aruba Networks");
        cic.put(284, "Baidu");
        cic.put(285, "Arendi AG");
        cic.put(286, "Skoda Auto a.s.");
        cic.put(287, "Volkswagen AG");
        cic.put(288, "Porsche AG");
        cic.put(289, "Sino Wealth Electronic Ltd.");
        cic.put(290, "AirTurn, Inc.");
        cic.put(291, "Kinsa, Inc");
        cic.put(292, "HID Global");
        cic.put(293, "SEAT es");
        cic.put(294, "Promethean Ltd.");
        cic.put(295, "Salutica Allied Solutions");
        cic.put(296, "GPSI Group Pty Ltd");
        cic.put(297, "Nimble Devices Oy");
        cic.put(298, "Changzhou Yongse Infotech Co., Ltd.");
        cic.put(299, "SportIQ");
        cic.put(300, "TEMEC Instruments B.V.");
        cic.put(301, "Sony Corporation");
        cic.put(302, "ASSA ABLOY");
        cic.put(303, "Clarion Co. Inc.");
        cic.put(304, "Warehouse Innovations");
        cic.put(305, "Cypress Semiconductor");
        cic.put(306, "MADS Inc");
        cic.put(307, "Blue Maestro Limited");
        cic.put(308, "Resolution Products, Ltd.");
        cic.put(309, "Aireware LLC");
        cic.put(310, "Silvair, Inc.");
        cic.put(311, "Prestigio Plaza Ltd.");
        cic.put(312, "NTEO Inc.");
        cic.put(313, "Focus Systems Corporation");
        cic.put(314, "Tencent Holdings Ltd.");
        cic.put(315, "Allegion");
        cic.put(316, "Murata Manufacturing Co., Ltd.");
        cic.put(317, "WirelessWERX");
        cic.put(318, "Nod, Inc.");
        cic.put(319, "B&B Manufacturing Company");
        cic.put(320, "Alpine Electronics (China) Co., Ltd");
        cic.put(321, "FedEx Services");
        cic.put(322, "Grape Systems Inc.");
        cic.put(323, "Bkon Connect");
        cic.put(324, "Lintech GmbH");
        cic.put(325, "Novatel Wireless");
        cic.put(326, "Ciright");
        cic.put(327, "Mighty Cast, Inc.");
        cic.put(328, "Ambimat Electronics");
        cic.put(329, "Perytons Ltd.");
        cic.put(330, "Tivoli Audio, LLC");
        cic.put(331, "Master Lock");
        cic.put(332, "Mesh-Net Ltd");
        cic.put(333, "HUIZHOU DESAY SV AUTOMOTIVE CO., LTD.");
        cic.put(334, "Tangerine, Inc.");
        cic.put(335, "B&W Group Ltd.");
        cic.put(336, "Pioneer Corporation");
        cic.put(337, "OnBeep");
        cic.put(338, "Vernier Software & Technology");
        cic.put(339, "ROL Ergo");
        cic.put(340, "Pebble Technology");
        cic.put(341, "NETATMO");
        cic.put(342, "Accumulate AB");
        cic.put(343, "Anhui Huami Information Technology Co., Ltd.");
        cic.put(344, "Inmite s.r.o.");
        cic.put(345, "ChefSteps, Inc.");
        cic.put(346, "micas AG");
        cic.put(347, "Biomedical Research Ltd.");
        cic.put(348, "Pitius Tec S.L.");
        cic.put(349, "Estimote, Inc.");
        cic.put(350, "Unikey Technologies, Inc.");
        cic.put(351, "Timer Cap Co.");
        cic.put(352, "AwoX");
        cic.put(353, "yikes");
        cic.put(354, "MADSGlobalNZ Ltd.");
        cic.put(355, "PCH International");
        cic.put(356, "Qingdao Yeelink Information Technology Co., Ltd.");
        cic.put(357, "Milwaukee Tool (Formally Milwaukee Electric Tools)");
        cic.put(358, "MISHIK Pte Ltd");
        cic.put(359, "Ascensia Diabetes Care US Inc.");
        cic.put(360, "Spicebox LLC");
        cic.put(361, "emberlight");
        cic.put(362, "Cooper-Atkins Corporation");
        cic.put(363, "Qblinks");
        cic.put(364, "MYSPHERA");
        cic.put(365, "LifeScan Inc");
        cic.put(366, "Volantic AB");
        cic.put(367, "Podo Labs, Inc");
        cic.put(368, "Roche Diabetes Care AG");
        cic.put(369, "Amazon Fulfillment Service");
        cic.put(370, "Connovate Technology Private Limited");
        cic.put(371, "Kocomojo, LLC");
        cic.put(372, "Everykey Inc.");
        cic.put(373, "Dynamic Controls");
        cic.put(374, "SentriLock");
        cic.put(375, "I-SYST inc.");
        cic.put(376, "CASIO COMPUTER CO., LTD.");
        cic.put(377, "LAPIS Semiconductor Co., Ltd.");
        cic.put(378, "Telemonitor, Inc.");
        cic.put(379, "taskit GmbH");
        cic.put(380, "Daimler AG");
        cic.put(381, "BatAndCat");
        cic.put(382, "BluDotz Ltd");
        cic.put(383, "XTel Wireless ApS");
        cic.put(384, "Gigaset Communications GmbH");
        cic.put(385, "Gecko Health Innovations, Inc.");
        cic.put(386, "HOP Ubiquitous");
        cic.put(387, "Walt Disney");
        cic.put(388, "Nectar");
        cic.put(389, "bel'apps LLC");
        cic.put(390, "CORE Lighting Ltd");
        cic.put(391, "Seraphim Sense Ltd");
        cic.put(392, "Unico RBC");
        cic.put(393, "Physical Enterprises Inc.");
        cic.put(394, "Able Trend Technology Limited");
        cic.put(395, "Konica Minolta, Inc.");
        cic.put(396, "Wilo SE");
        cic.put(397, "Extron Design Services");
        cic.put(398, "Fitbit, Inc.");
        cic.put(399, "Fireflies Systems");
        cic.put(400, "Intelletto Technologies Inc.");
        cic.put(401, "FDK CORPORATION");
        cic.put(402, "Cloudleaf, Inc");
        cic.put(403, "Maveric Automation LLC");
        cic.put(404, "Acoustic Stream Corporation");
        cic.put(405, "Zuli");
        cic.put(406, "Paxton Access Ltd");
        cic.put(407, "WiSilica Inc.");
        cic.put(408, "VENGIT Korlatolt Felelossegu Tarsasag");
        cic.put(409, "SALTO SYSTEMS S.L.");
        cic.put(410, "TRON Forum (formerly T-Engine Forum)");
        cic.put(411, "CUBETECH s.r.o.");
        cic.put(412, "Cokiya Incorporated");
        cic.put(413, "CVS Health");
        cic.put(414, "Ceruus");
        cic.put(415, "Strainstall Ltd");
        cic.put(416, "Channel Enterprises (HK) Ltd.");
        cic.put(417, "FIAMM");
        cic.put(418, "GIGALANE.CO.,LTD");
        cic.put(419, "EROAD");
        cic.put(420, "Mine Safety Appliances");
        cic.put(421, "Icon Health and Fitness");
        cic.put(422, "Asandoo GmbH");
        cic.put(423, "ENERGOUS CORPORATION");
        cic.put(424, "Taobao");
        cic.put(425, "Canon Inc.");
        cic.put(426, "Geophysical Technology Inc.");
        cic.put(427, "Facebook, Inc.");
        cic.put(428, "Nipro Diagnostics, Inc.");
        cic.put(429, "FlightSafety International");
        cic.put(430, "Earlens Corporation");
        cic.put(431, "Sunrise Micro Devices, Inc.");
        cic.put(432, "Star Micronics Co., Ltd.");
        cic.put(433, "Netizens Sp. z o.o.");
        cic.put(434, "Nymi Inc.");
        cic.put(435, "Nytec, Inc.");
        cic.put(436, "Trineo Sp. z o.o.");
        cic.put(437, "Nest Labs Inc.");
        cic.put(438, "LM Technologies Ltd");
        cic.put(439, "General Electric Company");
        cic.put(440, "i+D3 S.L.");
        cic.put(441, "HANA Micron");
        cic.put(442, "Stages Cycling LLC");
        cic.put(443, "Cochlear Bone Anchored Solutions AB");
        cic.put(444, "SenionLab AB");
        cic.put(445, "Syszone Co., Ltd");
        cic.put(446, "Pulsate Mobile Ltd.");
        cic.put(447, "Hong Kong HunterSun Electronic Limited");
        cic.put(448, "pironex GmbH");
        cic.put(449, "BRADATECH Corp.");
        cic.put(450, "Transenergooil AG");
        cic.put(451, "Bunch");
        cic.put(452, "DME Microelectronics");
        cic.put(453, "Bitcraze AB");
        cic.put(454, "HASWARE Inc.");
        cic.put(455, "Abiogenix Inc.");
        cic.put(456, "Poly-Control ApS");
        cic.put(457, "Avi-on");
        cic.put(458, "Laerdal Medical AS");
        cic.put(459, "Fetch My Pet");
        cic.put(460, "Sam Labs Ltd.");
        cic.put(461, "Chengdu Synwing Technology Ltd");
        cic.put(462, "HOUWA SYSTEM DESIGN, k.k.");
        cic.put(463, "BSH");
        cic.put(464, "Primus Inter Pares Ltd");
        cic.put(465, "August Home, Inc");
        cic.put(466, "Gill Electronics");
        cic.put(467, "Sky Wave Design");
        cic.put(468, "Newlab S.r.l.");
        cic.put(469, "ELAD srl");
        cic.put(470, "G-wearables inc.");
        cic.put(471, "Squadrone Systems Inc.");
        cic.put(472, "Code Corporation");
        cic.put(473, "Savant Systems LLC");
        cic.put(474, "Logitech International SA");
        cic.put(475, "Innblue Consulting");
        cic.put(476, "iParking Ltd.");
        cic.put(477, "Koninklijke Philips Electronics N.V.");
        cic.put(478, "Minelab Electronics Pty Limited");
        cic.put(479, "Bison Group Ltd.");
        cic.put(480, "Widex A/S");
        cic.put(481, "Jolla Ltd");
        cic.put(482, "Lectronix, Inc.");
        cic.put(483, "Caterpillar Inc");
        cic.put(484, "Freedom Innovations");
        cic.put(485, "Dynamic Devices Ltd");
        cic.put(486, "Technology Solutions (UK) Ltd");
        cic.put(487, "IPS Group Inc.");
        cic.put(488, "STIR");
        cic.put(489, "Sano, Inc.");
        cic.put(490, "Advanced Application Design, Inc.");
        cic.put(491, "AutoMap LLC");
        cic.put(492, "Spreadtrum Communications Shanghai Ltd");
        cic.put(493, "CuteCircuit LTD");
        cic.put(494, "Valeo Service");
        cic.put(495, "Fullpower Technologies, Inc.");
        cic.put(496, "KloudNation");
        cic.put(497, "Zebra Technologies Corporation");
        cic.put(498, "Itron, Inc.");
        cic.put(499, "The University of Tokyo");
        cic.put(500, "UTC Fire and Security");
        cic.put(501, "Cool Webthings Limited");
        cic.put(502, "DJO Global");
        cic.put(503, "Gelliner Limited");
        cic.put(504, "Anyka (Guangzhou) Microelectronics Technology Co, LTD");
        cic.put(505, "Medtronic Inc.");
        cic.put(506, "Gozio Inc.");
        cic.put(507, "Form Lifting, LLC");
        cic.put(508, "Wahoo Fitness, LLC");
        cic.put(509, "Kontakt Micro-Location Sp. z o.o.");
        cic.put(510, "Radio Systems Corporation");
        cic.put(511, "Freescale Semiconductor, Inc.");
        cic.put(512, "Verifone Systems Pte Ltd. Taiwan Branch");
        cic.put(513, "AR Timing");
        cic.put(514, "Rigado LLC");
        cic.put(515, "Kemppi Oy");
        cic.put(516, "Tapcentive Inc.");
        cic.put(517, "Smartbotics Inc.");
        cic.put(518, "Otter Products, LLC");
        cic.put(519, "STEMP Inc.");
        cic.put(520, "LumiGeek LLC");
        cic.put(521, "InvisionHeart Inc.");
        cic.put(522, "Macnica Inc.");
        cic.put(523, "Jaguar Land Rover Limited");
        cic.put(524, "CoroWare Technologies, Inc");
        cic.put(525, "Simplo Technology Co., LTD");
        cic.put(526, "Omron Healthcare Co., LTD");
        cic.put(527, "Comodule GMBH");
        cic.put(528, "ikeGPS");
        cic.put(529, "Telink Semiconductor Co. Ltd");
        cic.put(530, "Interplan Co., Ltd");
        cic.put(531, "Wyler AG");
        cic.put(532, "IK Multimedia Production srl");
        cic.put(533, "Lukoton Experience Oy");
        cic.put(534, "MTI Ltd");
        cic.put(535, "Tech4home, Lda");
        cic.put(536, "Hiotech AB");
        cic.put(537, "DOTT Limited");
        cic.put(538, "Blue Speck Labs, LLC");
        cic.put(539, "Cisco Systems, Inc");
        cic.put(540, "Mobicomm Inc");
        cic.put(541, "Edamic");
        cic.put(542, "Goodnet, Ltd");
        cic.put(543, "Luster Leaf Products Inc");
        cic.put(544, "Manus Machina BV");
        cic.put(545, "Mobiquity Networks Inc");
        cic.put(546, "Praxis Dynamics");
        cic.put(547, "Philip Morris Products S.A.");
        cic.put(548, "Comarch SA");
        cic.put(549, "Nestl Nespresso S.A.");
        cic.put(550, "Merlinia A/S");
        cic.put(551, "LifeBEAM Technologies");
        cic.put(552, "Twocanoes Labs, LLC");
        cic.put(553, "Muoverti Limited");
        cic.put(554, "Stamer Musikanlagen GMBH");
        cic.put(555, "Tesla Motors");
        cic.put(556, "Pharynks Corporation");
        cic.put(557, "Lupine");
        cic.put(558, "Siemens AG");
        cic.put(559, "Huami (Shanghai) Culture Communication CO., LTD");
        cic.put(560, "Foster Electric Company, Ltd");
        cic.put(561, "ETA SA");
        cic.put(562, "x-Senso Solutions Kft");
        cic.put(563, "Shenzhen SuLong Communication Ltd");
        cic.put(564, "FengFan (BeiJing) Technology Co, Ltd");
        cic.put(565, "Qrio Inc");
        cic.put(566, "Pitpatpet Ltd");
        cic.put(567, "MSHeli s.r.l.");
        cic.put(568, "Trakm8 Ltd");
        cic.put(569, "JIN CO, Ltd");
        cic.put(570, "Alatech Tehnology");
        cic.put(571, "Beijing CarePulse Electronic Technology Co, Ltd");
        cic.put(572, "Awarepoint");
        cic.put(573, "ViCentra B.V.");
        cic.put(574, "Raven Industries");
        cic.put(575, "WaveWare Technologies Inc.");
        cic.put(576, "Argenox Technologies");
        cic.put(577, "Bragi GmbH");
        cic.put(578, "16Lab Inc");
        cic.put(579, "Masimo Corp");
        cic.put(580, "Iotera Inc");
        cic.put(581, "Endress+Hauser");
        cic.put(582, "ACKme Networks, Inc.");
        cic.put(583, "FiftyThree Inc.");
        cic.put(584, "Parker Hannifin Corp");
        cic.put(585, "Transcranial Ltd");
        cic.put(586, "Uwatec AG");
        cic.put(587, "Orlan LLC");
        cic.put(588, "Blue Clover Devices");
        cic.put(589, "M-Way Solutions GmbH");
        cic.put(590, "Microtronics Engineering GmbH");
        cic.put(591, "Schneider Schreibgerte GmbH");
        cic.put(592, "Sapphire Circuits LLC");
        cic.put(593, "Lumo Bodytech Inc.");
        cic.put(594, "UKC Technosolution");
        cic.put(595, "Xicato Inc.");
        cic.put(596, "Playbrush");
        cic.put(597, "Dai Nippon Printing Co., Ltd.");
        cic.put(598, "G24 Power Limited");
        cic.put(599, "AdBabble Local Commerce Inc.");
        cic.put(600, "Devialet SA");
        cic.put(601, "ALTYOR");
        cic.put(602, "University of Applied Sciences Valais/Haute Ecole Valaisanne");
        cic.put(603, "Five Interactive, LLC dba Zendo");
        cic.put(604, "NetEaseHangzhouNetwork co.Ltd.");
        cic.put(605, "Lexmark International Inc.");
        cic.put(606, "Fluke Corporation");
        cic.put(607, "Yardarm Technologies");
        cic.put(608, "SensaRx");
        cic.put(609, "SECVRE GmbH");
        cic.put(610, "Glacial Ridge Technologies");
        cic.put(611, "Identiv, Inc.");
        cic.put(612, "DDS, Inc.");
        cic.put(613, "SMK Corporation");
        cic.put(614, "Schawbel Technologies LLC");
        cic.put(615, "XMI Systems SA");
        cic.put(616, "Cerevo");
        cic.put(617, "Torrox GmbH & Co KG");
        cic.put(618, "Gemalto");
        cic.put(619, "DEKA Research & Development Corp.");
        cic.put(620, "Domster Tadeusz Szydlowski");
        cic.put(621, "Technogym SPA");
        cic.put(622, "FLEURBAEY BVBA");
        cic.put(623, "Aptcode Solutions");
        cic.put(624, "LSI ADL Technology");
        cic.put(625, "Animas Corp");
        cic.put(626, "Alps Electric Co., Ltd.");
        cic.put(627, "OCEASOFT");
        cic.put(628, "Motsai Research");
        cic.put(629, "Geotab");
        cic.put(630, "E.G.O. Elektro-Gertebau GmbH");
        cic.put(631, "bewhere inc");
        cic.put(632, "Johnson Outdoors Inc");
        cic.put(633, "steute Schaltgerate GmbH & Co. KG");
        cic.put(634, "Ekomini inc.");
        cic.put(635, "DEFA AS");
        cic.put(636, "Aseptika Ltd");
        cic.put(637, "HUAWEI Technologies Co., Ltd. ( )");
        cic.put(638, "HabitAware, LLC");
        cic.put(639, "ruwido austria gmbh");
        cic.put(640, "ITEC corporation");
        cic.put(641, "StoneL");
        cic.put(642, "Sonova AG");
        cic.put(643, "Maven Machines, Inc.");
        cic.put(644, "Synapse Electronics");
        cic.put(645, "Standard Innovation Inc.");
        cic.put(646, "RF Code, Inc.");
        cic.put(647, "Wally Ventures S.L.");
        cic.put(648, "Willowbank Electronics Ltd");
        cic.put(649, "SK Telecom");
        cic.put(650, "Jetro AS");
        cic.put(651, "Code Gears LTD");
        cic.put(652, "NANOLINK APS");
        cic.put(653, "IF, LLC");
        cic.put(654, "RF Digital Corp");
        cic.put(655, "Church & Dwight Co., Inc");
        cic.put(656, "Multibit Oy");
        cic.put(657, "CliniCloud Inc");
        cic.put(658, "SwiftSensors");
        cic.put(659, "Blue Bite");
        cic.put(660, "ELIAS GmbH");
        cic.put(661, "Sivantos GmbH");
        cic.put(662, "Petzl");
        cic.put(663, "storm power ltd");
        cic.put(664, "EISST Ltd");
        cic.put(665, "Inexess Technology Simma KG");
        cic.put(666, "Currant, Inc.");
        cic.put(667, "C2 Development, Inc.");
        cic.put(668, "Blue Sky Scientific, LLC");
        cic.put(669, "ALOTTAZS LABS, LLC");
        cic.put(670, "Kupson spol. s r.o.");
        cic.put(671, "Areus Engineering GmbH");
        cic.put(672, "Impossible Camera GmbH");
        cic.put(673, "InventureTrack Systems");
        cic.put(674, "LockedUp");
        cic.put(675, "Itude");
        cic.put(676, "Pacific Lock Company");
        cic.put(677, "Tendyron Corporation ( )");
        cic.put(678, "Robert Bosch GmbH");
        cic.put(679, "Illuxtron international B.V.");
        cic.put(680, "miSport Ltd.");
        cic.put(681, "Chargelib");
        cic.put(682, "Doppler Lab");
        cic.put(683, "BBPOS Limited");
        cic.put(684, "RTB Elektronik GmbH & Co. KG");
        cic.put(685, "Rx Networks, Inc.");
        cic.put(686, "WeatherFlow, Inc.");
        cic.put(687, "Technicolor USA Inc.");
        cic.put(688, "Bestechnic(Shanghai),Ltd");
        cic.put(689, "Raden Inc");
        cic.put(690, "JouZen Oy");
        cic.put(691, "CLABER S.P.A.");
        cic.put(692, "Hyginex, Inc.");
        cic.put(693, "HANSHIN ELECTRIC RAILWAY CO.,LTD.");
        cic.put(694, "Schneider Electric");
        cic.put(695, "Oort Technologies LLC");
        cic.put(696, "Chrono Therapeutics");
        cic.put(697, "Rinnai Corporation");
        cic.put(698, "Swissprime Technologies AG");
        cic.put(699, "Koha.,Co.Ltd");
        cic.put(700, "Genevac Ltd");
        cic.put(701, "Chemtronics");
        cic.put(702, "Seguro Technology Sp. z o.o.");
        cic.put(703, "Redbird Flight Simulations");
        cic.put(704, "Dash Robotics");
        cic.put(705, "LINE Corporation");
        cic.put(706, "Guillemot Corporation");
        cic.put(707, "Techtronic Power Tools Technology Limited");
        cic.put(708, "Wilson Sporting Goods");
        cic.put(709, "Lenovo (Singapore) Pte Ltd. ( )");
        cic.put(710, "Ayatan Sensors");
        cic.put(711, "Electronics Tomorrow Limited");
        cic.put(712, "VASCO Data Security International, Inc.");
        cic.put(713, "PayRange Inc.");
        cic.put(714, "ABOV Semiconductor");
        cic.put(715, "AINA-Wireless Inc.");
        cic.put(716, "Eijkelkamp Soil & Water");
        cic.put(717, "BMA ergonomics b.v.");
        cic.put(718, "Teva Branded Pharmaceutical Products R&D, Inc.");
        cic.put(719, "Anima");
        cic.put(720, "3M");
        cic.put(721, "Empatica Srl");
        cic.put(722, "Afero, Inc.");
        cic.put(723, "Powercast Corporation");
        cic.put(724, "Secuyou ApS");
        cic.put(725, "OMRON Corporation");
        cic.put(726, "Send Solutions");
        cic.put(727, "NIPPON SYSTEMWARE CO.,LTD.");
        cic.put(728, "Neosfar");
        cic.put(729, "Fliegl Agrartechnik GmbH");
        cic.put(730, "Gilvader");
        cic.put(731, "Digi International Inc (R)");
        cic.put(732, "DeWalch Technologies, Inc.");
        cic.put(733, "Flint Rehabilitation Devices, LLC");
        cic.put(734, "Samsung SDS Co., Ltd.");
        cic.put(735, "Blur Product Development");
        cic.put(736, "University of Michigan");
        cic.put(737, "Victron Energy BV");
        cic.put(738, "NTT docomo");
        cic.put(739, "Carmanah Technologies Corp.");
        cic.put(740, "Bytestorm Ltd.");
        cic.put(741, "Espressif Incorporated ( () )");
        cic.put(742, "Unwire");
        cic.put(743, "Connected Yard, Inc.");
        cic.put(744, "American Music Environments");
        cic.put(745, "Sensogram Technologies, Inc.");
        cic.put(746, "Fujitsu Limited");
        cic.put(747, "Ardic Technology");
        cic.put(748, "Delta Systems, Inc");
        cic.put(749, "HTC Corporation");
        cic.put(750, "Citizen Holdings Co., Ltd.");
        cic.put(751, "SMART-INNOVATION.inc");
        cic.put(752, "Blackrat Software");
        cic.put(753, "The Idea Cave, LLC");
        cic.put(754, "GoPro, Inc.");
        cic.put(755, "AuthAir, Inc");
        cic.put(756, "Vensi, Inc.");
        cic.put(757, "Indagem Tech LLC");
        cic.put(758, "Intemo Technologies");
        cic.put(759, "DreamVisions co., Ltd.");
        cic.put(760, "Runteq Oy Ltd");
        cic.put(761, "IMAGINATION TECHNOLOGIES LTD");
        cic.put(762, "CoSTAR TEchnologies");
        cic.put(763, "Clarius Mobile Health Corp.");
        cic.put(764, "Shanghai Frequen Microelectronics Co., Ltd.");
        cic.put(765, "Uwanna, Inc.");
        cic.put(766, "Lierda Science & Technology Group Co., Ltd.");
        cic.put(767, "Silicon Laboratories");
        cic.put(768, "World Moto Inc.");
        cic.put(769, "Giatec Scientific Inc.");
        cic.put(770, "Loop Devices, Inc");
        cic.put(771, "IACA electronique");
        cic.put(772, "Martians Inc");
        cic.put(773, "Swipp ApS");
        cic.put(774, "Life Laboratory Inc.");
        cic.put(775, "FUJI INDUSTRIAL CO.,LTD.");
        cic.put(776, "Surefire, LLC");
        cic.put(777, "Dolby Labs");
        cic.put(778, "Ellisys");
        cic.put(779, "Magnitude Lighting Converters");
        cic.put(780, "Hilti AG");
        cic.put(781, "Devdata S.r.l.");
        cic.put(782, "Deviceworx");
        cic.put(783, "Shortcut Labs");
        cic.put(784, "SGL Italia S.r.l.");
        cic.put(785, "PEEQ DATA");
        cic.put(786, "Ducere Technologies Pvt Ltd");
        cic.put(787, "DiveNav, Inc.");
        cic.put(788, "RIIG AI Sp. z o.o.");
        cic.put(789, "Thermo Fisher Scientific");
        cic.put(790, "AG Measurematics Pvt. Ltd.");
        cic.put(791, "CHUO Electronics CO., LTD.");
        cic.put(792, "Aspenta International");
        cic.put(793, "Eugster Frismag AG");
        cic.put(794, "Amber wireless GmbH");
        cic.put(795, "HQ Inc");
        cic.put(796, "Lab Sensor Solutions");
        cic.put(797, "Enterlab ApS");
        cic.put(798, "Eyefi, Inc.");
        cic.put(799, "MetaSystem S.p.A.");
        cic.put(800, "SONO ELECTRONICS. CO., LTD");
        cic.put(801, "Jewelbots");
        cic.put(802, "Compumedics Limited");
        cic.put(803, "Rotor Bike Components");
        cic.put(804, "Astro, Inc.");
        cic.put(805, "Amotus Solutions");
        cic.put(806, "Healthwear Technologies (Changzhou)Ltd");
        cic.put(807, "Essex Electronics");
        cic.put(808, "Grundfos A/S");
        cic.put(809, "Eargo, Inc.");
        cic.put(810, "Electronic Design Lab");
        cic.put(811, "ESYLUX");
        cic.put(812, "NIPPON SMT.CO.,Ltd");
        cic.put(813, "BM innovations GmbH");
        cic.put(814, "indoormap");
        cic.put(815, "OttoQ Inc");
        cic.put(816, "North Pole Engineering");
        cic.put(817, "3flares Technologies Inc.");
        cic.put(818, "Electrocompaniet A.S.");
        cic.put(819, "Mul-T-Lock");
        cic.put(820, "Corentium AS");
        cic.put(821, "Enlighted Inc");
        cic.put(822, "GISTIC");
        cic.put(823, "AJP2 Holdings, LLC");
        cic.put(824, "COBI GmbH");
        cic.put(825, "Blue Sky Scientific, LLC");
        cic.put(826, "Appception, Inc.");
        cic.put(827, "Courtney Thorne Limited");
        cic.put(828, "Virtuosys");
        cic.put(829, "TPV Technology Limited");
        cic.put(830, "Monitra SA");
        cic.put(831, "Automation Components, Inc.");
        cic.put(832, "Letsense s.r.l.");
        cic.put(833, "Etesian Technologies LLC");
        cic.put(834, "GERTEC BRASIL LTDA.");
        cic.put(835, "Drekker Development Pty. Ltd.");
        cic.put(836, "Whirl Inc");
        cic.put(837, "Locus Positioning");
        cic.put(838, "Acuity Brands Lighting, Inc");
        cic.put(839, "Prevent Biometrics");
        cic.put(840, "Arioneo");
        cic.put(841, "VersaMe");
        cic.put(842, "Vaddio");
        cic.put(843, "Libratone A/S");
        cic.put(844, "HM Electronics, Inc.");
        cic.put(845, "TASER International, Inc.");
        cic.put(846, "SafeTrust Inc.");
        cic.put(847, "Heartland Payment Systems");
        cic.put(848, "Bitstrata Systems Inc.");
        cic.put(849, "Pieps GmbH");
        cic.put(850, "iRiding(Xiamen)Technology Co.,Ltd.");
        cic.put(851, "Alpha Audiotronics, Inc.");
        cic.put(852, "TOPPAN FORMS CO.,LTD.");
        cic.put(853, "Sigma Designs, Inc.");
        cic.put(854, "Spectrum Brands, Inc.");
        cic.put(855, "Polymap Wireless");
        cic.put(856, "MagniWare Ltd.");
        cic.put(857, "Novotec Medical GmbH");
        cic.put(858, "Medicom Innovation Partner a/s");
        cic.put(859, "Matrix Inc.");
        cic.put(860, "Eaton Corporation");
        cic.put(861, "KYS");
        cic.put(862, "Naya Health, Inc.");
        cic.put(863, "Acromag");
        cic.put(864, "Insulet Corporation");
        cic.put(865, "Wellinks Inc.");
        cic.put(866, "ON Semiconductor");
        cic.put(867, "FREELAP SA");
        cic.put(868, "Favero Electronics Srl");
        cic.put(869, "BioMech Sensor LLC");
        cic.put(870, "BOLTT Sports technologies Private limited");
        cic.put(871, "Saphe International");
        cic.put(872, "Metormote AB");
        cic.put(873, "littleBits");
        cic.put(874, "SetPoint Medical");
        cic.put(875, "BRControls Products BV");
        cic.put(876, "Zipcar");
        cic.put(877, "AirBolt Pty Ltd");
        cic.put(878, "KeepTruckin Inc");
        cic.put(879, "Motiv, Inc.");
        cic.put(880, "Wazombi Labs O");
        cic.put(881, "ORBCOMM");
        cic.put(882, "Nixie Labs, Inc.");
        cic.put(883, "AppNearMe Ltd");
        cic.put(884, "Holman Industries");
        cic.put(885, "Expain AS");
        cic.put(886, "Electronic Temperature Instruments Ltd");
        cic.put(887, "Plejd AB");
        cic.put(888, "Propeller Health");
        cic.put(889, "Shenzhen iMCO Electronic Technology Co.,Ltd");
        cic.put(890, "Algoria");
        cic.put(891, "Apption Labs Inc.");
        cic.put(892, "Cronologics Corporation");
        cic.put(893, "MICRODIA Ltd.");
        cic.put(894, "lulabytes S.L.");
        cic.put(895, "Nestec S.A.");
        cic.put(896, "LLC \"MEGA-F service\"");
        cic.put(897, "Sharp Corporation");
        cic.put(898, "Precision Outcomes Ltd");
        cic.put(899, "Kronos Incorporated");
        cic.put(900, "OCOSMOS Co., Ltd.");
        cic.put(901, "Embedded Electronic Solutions Ltd. dba e2Solutions");
        cic.put(902, "Aterica Inc.");
        cic.put(903, "BluStor PMC, Inc.");
        cic.put(904, "Kapsch TrafficCom AB");
        cic.put(905, "ActiveBlu Corporation");
        cic.put(906, "Kohler Mira Limited");
        cic.put(907, "Noke");
        cic.put(908, "Appion Inc.");
        cic.put(909, "Resmed Ltd");
        cic.put(910, "Crownstone B.V.");
        cic.put(911, "Xiaomi Inc.");
        cic.put(912, "INFOTECH s.r.o.");
        cic.put(913, "Thingsquare AB");
        cic.put(914, "T&D");
        cic.put(915, "LAVAZZA S.p.A.");
        cic.put(916, "Netclearance Systems, Inc.");
        cic.put(917, "SDATAWAY");
        cic.put(918, "BLOKS GmbH");
        cic.put(919, "LEGO System A/S");
        cic.put(920, "Thetatronics Ltd");
        cic.put(921, "Nikon Corporation");
        cic.put(922, "NeST");
        cic.put(923, "South Silicon Valley Microelectronics");
        cic.put(924, "ALE International");
        cic.put(925, "CareView Communications, Inc.");
        cic.put(926, "SchoolBoard Limited");
        cic.put(927, "Molex Corporation");
        cic.put(928, "IVT Wireless Limited");
        cic.put(929, "Alpine Labs LLC");
        cic.put(930, "Candura Instruments");
        cic.put(931, "SmartMovt Technology Co., Ltd");
        cic.put(932, "Token Zero Ltd");
        cic.put(933, "ACE CAD Enterprise Co., Ltd. (ACECAD)");
        cic.put(934, "Medela, Inc");
        cic.put(935, "AeroScout");
        cic.put(936, "Esrille Inc.");
        cic.put(937, "THINKERLY SRL");
        cic.put(938, "Exon Sp. z o.o.");
        cic.put(939, "Meizu Technology Co., Ltd.");
        cic.put(940, "Smablo LTD");
        cic.put(941, "XiQ");
        cic.put(942, "Allswell Inc.");
        cic.put(943, "Comm-N-Sense Corp DBA Verigo");
        cic.put(944, "VIBRADORM GmbH");
        cic.put(945, "Otodata Wireless Network Inc.");
        cic.put(946, "Propagation Systems Limited");
        cic.put(947, "Midwest Instruments & Controls");
        cic.put(948, "Alpha Nodus, inc.");
        cic.put(949, "petPOMM, Inc");
        cic.put(950, "Mattel");
        cic.put(951, "Airbly Inc.");
        cic.put(952, "A-Safe Limited");
        cic.put(953, "FREDERIQUE CONSTANT SA");
        cic.put(954, "Maxscend Microelectronics Company Limited");
        cic.put(955, "Abbott Diabetes Care");
        cic.put(956, "ASB Bank Ltd");
        cic.put(957, "amadas");
        cic.put(958, "Applied Science, Inc.");
        cic.put(959, "iLumi Solutions Inc.");
        cic.put(960, "Arch Systems Inc.");
        cic.put(961, "Ember Technologies, Inc.");
        cic.put(962, "Snapchat Inc");
        cic.put(963, "Casambi Technologies Oy");
        cic.put(964, "Pico Technology Inc.");
        cic.put(965, "St. Jude Medical, Inc.");
        cic.put(966, "Intricon");
        cic.put(967, "Structural Health Systems, Inc.");
        cic.put(968, "Avvel International");
        cic.put(969, "Gallagher Group");
        cic.put(970, "In2things Automation Pvt. Ltd.");
        cic.put(971, "SYSDEV Srl");
        cic.put(972, "Vonkil Technologies Ltd");
        cic.put(973, "Wynd Technologies, Inc.");
        cic.put(974, "CONTRINEX S.A.");
        cic.put(975, "MIRA, Inc.");
        cic.put(976, "Watteam Ltd");
        cic.put(977, "Density Inc.");
        cic.put(978, "IOT Pot India Private Limited");
        cic.put(979, "Sigma Connectivity AB");
        cic.put(980, "PEG PEREGO SPA");
        cic.put(981, "Wyzelink Systems Inc.");
        cic.put(982, "Yota Devices LTD");
        cic.put(983, "FINSECUR");
        cic.put(984, "Zen-Me Labs Ltd");
        cic.put(985, "3IWare Co., Ltd.");
        cic.put(986, "EnOcean GmbH");
        cic.put(987, "Instabeat, Inc");
        cic.put(988, "Nima Labs");
        cic.put(989, "Andreas Stihl AG & Co. KG");
        cic.put(990, "Nathan Rhoades LLC");
        cic.put(991, "Grob Technologies, LLC");
        cic.put(992, "Actions (Zhuhai) Technology Co., Limited");
        cic.put(993, "SPD Development Company Ltd");
        cic.put(994, "Sensoan Oy");
        cic.put(995, "Qualcomm Life Inc");
        cic.put(996, "Chip-ing AG");
        cic.put(997, "ffly4u");
        cic.put(998, "IoT Instruments Oy");
        cic.put(999, "TRUE Fitness Technology");
        cic.put(1000, "Reiner Kartengeraete GmbH & Co. KG.");
        cic.put(1001, "SHENZHEN LEMONJOY TECHNOLOGY CO., LTD.");
        cic.put(1002, "Hello Inc.");
        cic.put(1003, "Evollve Inc.");
        cic.put(1004, "Jigowatts Inc.");
        cic.put(1005, "BASIC MICRO.COM,INC.");
        cic.put(1006, "CUBE TECHNOLOGIES");
        cic.put(1007, "foolography GmbH");
        cic.put(1008, "CLINK");
        cic.put(1009, "Hestan Smart Cooking Inc.");
        cic.put(1010, "WindowMaster A/S");
        cic.put(1011, "Flowscape AB");
        cic.put(1012, "PAL Technologies Ltd");
        cic.put(1013, "WHERE, Inc.");
        cic.put(1014, "Iton Technology Corp.");
        cic.put(1015, "Owl Labs Inc.");
        cic.put(1016, "Rockford Corp.");
        cic.put(1017, "Becon Technologies Co.,Ltd.");
        cic.put(1018, "Vyassoft Technologies Inc");
        cic.put(1019, "Nox Medical");
        cic.put(1020, "Kimberly-Clark");
        cic.put(1021, "Trimble Navigation Ltd.");
        cic.put(1022, "Littelfuse");
        cic.put(1023, "Withings");
        cic.put(1024, "i-developer IT Beratung UG");
        cic.put(1025, "");
        cic.put(1026, "Sears Holdings Corporation");
        cic.put(1027, "Gantner Electronic GmbH");
        cic.put(1028, "Authomate Inc");
        cic.put(1029, "Vertex International, Inc.");
        cic.put(1030, "Airtago");
        cic.put(1031, "Swiss Audio SA");
        cic.put(1032, "ToGetHome Inc.");
        cic.put(1033, "AXIS");
        cic.put(1034, "Openmatics");
        cic.put(1035, "Jana Care Inc.");
        cic.put(1036, "Senix Corporation");
        cic.put(1037, "NorthStar Battery Company, LLC");
        cic.put(1038, "SKF (U.K.) Limited");
        cic.put(1039, "CO-AX Technology, Inc.");
        cic.put(1040, "Fender Musical Instruments");
        cic.put(1041, "Luidia Inc");
        cic.put(1042, "SEFAM");
        cic.put(1043, "Wireless Cables Inc");
        cic.put(1044, "Lightning Protection International Pty Ltd");
        cic.put(1045, "Uber Technologies Inc");
        cic.put(1046, "SODA GmbH");
        cic.put(1047, "Fatigue Science");
        cic.put(1048, "Alpine Electronics Inc.");
        cic.put(1049, "Novalogy LTD");
        cic.put(1050, "Friday Labs Limited");
        cic.put(1051, "OrthoAccel Technologies");
        cic.put(1052, "WaterGuru, Inc.");
        cic.put(1053, "Benning Elektrotechnik und Elektronik GmbH & Co. KG");
        cic.put(1054, "Dell Computer Corporation");
        cic.put(1055, "Kopin Corporation");
        cic.put(1056, "TecBakery GmbH");
        cic.put(1057, "Backbone Labs, Inc.");
        cic.put(1058, "DELSEY SA");
        cic.put(1059, "Chargifi Limited");
        cic.put(1060, "Trainesense Ltd.");
        cic.put(1061, "Unify Software and Solutions GmbH & Co. KG");
        cic.put(1062, "Husqvarna AB");
        cic.put(1063, "Focus fleet and fuel management inc");
        cic.put(1064, "SmallLoop, LLC");
        cic.put(1065, "Prolon Inc.");
        cic.put(1066, "BD Medical");
        cic.put(1067, "iMicroMed Incorporated");
        cic.put(1068, "Ticto N.V.");
        cic.put(1069, "Meshtech AS");
        cic.put(1070, "MemCachier Inc.");
        cic.put(1071, "Danfoss A/S");
        cic.put(1072, "SnapStyk Inc.");
        cic.put(1073, "Amway Corporation");
        cic.put(1074, "Silk Labs, Inc.");
        cic.put(1075, "Pillsy Inc.");
        cic.put(1076, "Hatch Baby, Inc.");
        cic.put(1077, "Blocks Wearables Ltd.");
        cic.put(1078, "Drayson Technologies (Europe) Limited");
        cic.put(1079, "eBest IOT Inc.");
        cic.put(1080, "Helvar Ltd");
        cic.put(1081, "Radiance Technologies");
        cic.put(1082, "Nuheara Limited");
        cic.put(1083, "Appside co., ltd.");
        cic.put(1084, "DeLaval");
        cic.put(1085, "Coiler Corporation");
        cic.put(1086, "Thermomedics, Inc.");
        cic.put(1087, "Tentacle Sync GmbH");
        cic.put(1088, "Valencell, Inc.");
        cic.put(1089, "iProtoXi Oy");
        cic.put(1090, "SECOM CO., LTD.");
        cic.put(1091, "Tucker International LLC");
        cic.put(1092, "Metanate Limited");
        cic.put(1093, "Kobian Canada Inc.");
        cic.put(1094, "NETGEAR, Inc.");
        cic.put(1095, "Fabtronics Australia Pty Ltd");
        cic.put(1096, "Grand Centrix GmbH");
        cic.put(1097, "1UP USA.com llc");
        cic.put(1098, "SHIMANO INC.");
        cic.put(1099, "Nain Inc.");
        cic.put(1100, "LifeStyle Lock, LLC");
        cic.put(1101, "VEGA Grieshaber KG");
        cic.put(1102, "Xtrava Inc.");
        cic.put(1103, "TTS Tooltechnic Systems AG & Co. KG");
        cic.put(1104, "Teenage Engineering AB");
        cic.put(1105, "Tunstall Nordic AB");
        cic.put(1106, "Svep Design Center AB");
        cic.put(1107, "GreenPeak Technologies BV");
        cic.put(1108, "Sphinx Electronics GmbH & Co KG");
        cic.put(1109, "Atomation");
        cic.put(1110, "Nemik Consulting Inc");
        cic.put(1111, "RF INNOVATION");
        cic.put(1112, "Mini Solution Co., Ltd.");
        cic.put(1113, "Lumenetix, Inc");
        cic.put(1114, "2048450 Ontario Inc");
        cic.put(1115, "SPACEEK LTD");
        cic.put(1116, "Delta T Corporation");
        cic.put(1117, "Boston Scientific Corporation");
        cic.put(1118, "Nuviz, Inc.");
        cic.put(1119, "Real Time Automation, Inc.");
        cic.put(1120, "Kolibree");
        cic.put(1121, "vhf elektronik GmbH");
        cic.put(1122, "Bonsai Systems GmbH");
        cic.put(1123, "Fathom Systems Inc.");
        cic.put(1124, "Bellman & Symfon");
        cic.put(1125, "International Forte Group LLC");
        cic.put(1126, "CycleLabs Solutions inc.");
        cic.put(1127, "Codenex Oy");
        cic.put(1128, "Kynesim Ltd");
        cic.put(1129, "Palago AB");
        cic.put(1130, "INSIGMA INC.");
        cic.put(1131, "PMD Solutions");
        cic.put(1132, "Qingdao Realtime Technology Co., Ltd.");
        cic.put(1133, "BEGA Gantenbrink-Leuchten KG");
        cic.put(1134, "Pambor Ltd.");
        cic.put(1135, "Develco Products A/S");
        cic.put(1136, "iDesign s.r.l.");
        cic.put(1137, "TiVo Corp");
        cic.put(1138, "Control-J Pty Ltd");
        cic.put(1139, "Steelcase, Inc.");
        cic.put(1140, "iApartment co., ltd.");
        cic.put(1141, "Icom inc.");
        cic.put(1142, "Oxstren Wearable Technologies Private Limited");
        cic.put(1143, "Blue Spark Technologies");
        cic.put(1144, "FarSite Communications Limited");
        cic.put(1145, "mywerk system GmbH");
        cic.put(1146, "Sinosun Technology Co., Ltd.");
        cic.put(1147, "MIYOSHI ELECTRONICS CORPORATION");
        cic.put(1148, "POWERMAT LTD");
        cic.put(1149, "Occly LLC");
        cic.put(1150, "OurHub Dev IvS");
        cic.put(1151, "Pro-Mark, Inc.");
        cic.put(1152, "Dynometrics Inc.");
        cic.put(1153, "Quintrax Limited");
        cic.put(1154, "POS Tuning Udo Vosshenrich GmbH & Co. KG");
        cic.put(1155, "Multi Care Systems B.V.");
        cic.put(1156, "Revol Technologies Inc");
        cic.put(1157, "SKIDATA AG");
        cic.put(1158, "DEV TECNOLOGIA INDUSTRIA, COMERCIO E MANUTENCAO DE EQUIPAMENTOS LTDA. - ME");
        cic.put(1159, "Centrica Connected Home");
        cic.put(1160, "Automotive Data Solutions Inc");
        cic.put(1161, "Igarashi Engineering");
        cic.put(1162, "Taelek Oy");
        cic.put(1163, "CP Electronics Limited");
        cic.put(1164, "Vectronix AG");
        cic.put(1165, "S-Labs Sp. z o.o.");
        cic.put(1166, "Companion Medical, Inc.");
        cic.put(1167, "BlueKitchen GmbH");
        cic.put(1168, "Matting AB");
        cic.put(1169, "SOREX - Wireless Solutions GmbH");
        cic.put(1170, "ADC Technology, Inc.");
        cic.put(1171, "Lynxemi Pte Ltd");
        cic.put(1172, "SENNHEISER electronic GmbH & Co. KG");
        cic.put(1173, "LMT Mercer Group, Inc");
        cic.put(1174, "Polymorphic Labs LLC");
        cic.put(1175, "Cochlear Limited");
        cic.put(1176, "METER Group, Inc. USA");
        cic.put(1177, "Ruuvi Innovations Ltd.");
        cic.put(1178, "Situne AS");
        cic.put(1179, "nVisti, LLC");
        cic.put(1180, "DyOcean");
        cic.put(1181, "Uhlmann & Zacher GmbH");
        cic.put(1182, "AND!XOR LLC");
        cic.put(1183, "tictote AB");
        cic.put(1184, "Vypin, LLC");
        cic.put(1185, "PNI Sensor Corporation");
        cic.put(1186, "ovrEngineered, LLC");
        cic.put(1187, "GT-tronics HK Ltd");
        cic.put(1188, "Herbert Waldmann GmbH & Co. KG");
        cic.put(1189, "Guangzhou FiiO Electronics Technology Co.,Ltd");
        cic.put(1190, "Vinetech Co., Ltd");
        cic.put(1191, "Dallas Logic Corporation");
        cic.put(1192, "BioTex, Inc.");
        cic.put(1193, "DISCOVERY SOUND TECHNOLOGY, LLC");
        cic.put(1194, "LINKIO SAS");
        cic.put(1195, "Harbortronics, Inc.");
        cic.put(1196, "Undagrid B.V.");
        cic.put(1197, "Shure Inc");
        cic.put(1198, "ERM Electronic Systems LTD");
        cic.put(1199, "BIOROWER Handelsagentur GmbH");
        cic.put(1200, "Weba Sport und Med. Artikel GmbH");
        cic.put(1201, "Kartographers Technologies Pvt. Ltd.");
        cic.put(1202, "The Shadow on the Moon");
        cic.put(1203, "mobike (Hong Kong) Limited");
        cic.put(1204, "Inuheat Group AB");
        cic.put(1205, "Swiftronix AB");
        cic.put(1206, "Diagnoptics Technologies");
        cic.put(1207, "Analog Devices, Inc.");
        cic.put(1208, "Soraa Inc.");
        cic.put(1209, "CSR Building Products Limited");
        cic.put(1210, "Crestron Electronics, Inc.");
        cic.put(1211, "Neatebox Ltd");
        cic.put(1212, "Draegerwerk AG & Co. KGaA");
        cic.put(1213, "AlbynMedical");
        cic.put(1214, "Averos FZCO");
        cic.put(1215, "VIT Initiative, LLC");
        cic.put(1216, "Statsports International");
        cic.put(1217, "Sospitas, s.r.o.");
        cic.put(1218, "Dmet Products Corp.");
        cic.put(1219, "Mantracourt Electronics Limited");
        cic.put(1220, "TeAM Hutchins AB");
        cic.put(1221, "Seibert Williams Glass, LLC");
        cic.put(1222, "Insta GmbH");
        cic.put(1223, "Svantek Sp. z o.o.");
        cic.put(1224, "Shanghai Flyco Electrical Appliance Co., Ltd.");
        cic.put(1225, "Thornwave Labs Inc");
        cic.put(1226, "Steiner-Optik GmbH");
        cic.put(1227, "Novo Nordisk A/S");
        cic.put(1228, "Enflux Inc.");
        cic.put(1229, "Safetech Products LLC");
        cic.put(1230, "GOOOLED S.R.L.");
        cic.put(1231, "DOM Sicherheitstechnik GmbH & Co. KG");
        cic.put(1232, "Olympus Corporation");
        cic.put(1233, "KTS GmbH");
        cic.put(1234, "Anloq Technologies Inc.");
        cic.put(1235, "Queercon, Inc");
        cic.put(1236, "5th Element Ltd");
        cic.put(1237, "Gooee Limited");
        cic.put(1238, "LUGLOC LLC");
        cic.put(1239, "Blincam, Inc.");
        cic.put(1240, "FUJIFILM Corporation");
        cic.put(1241, "RandMcNally");
        cic.put(1242, "Franceschi Marina snc");
        cic.put(1243, "Engineered Audio, LLC.");
        cic.put(1244, "IOTTIVE (OPC) PRIVATE LIMITED");
        cic.put(1245, "4MOD Technology");
        cic.put(1246, "Lutron Electronics Co., Inc.");
        cic.put(1247, "Emerson");
        cic.put(1248, "Guardtec, Inc.");
        cic.put(1249, "REACTEC LIMITED");
        cic.put(1250, "EllieGrid");
        cic.put(1251, "Under Armour");
        cic.put(1252, "Woodenshark");
        cic.put(1253, "Avack Oy");
        cic.put(1254, "Smart Solution Technology, Inc.");
        cic.put(1255, "REHABTRONICS INC.");
        cic.put(1256, "STABILO International");
        cic.put(1257, "Busch Jaeger Elektro GmbH");
        cic.put(1258, "Pacific Bioscience Laboratories, Inc");
        cic.put(1259, "Bird Home Automation GmbH");
        cic.put(1260, "Motorola Solutions");
        cic.put(1261, "R9 Technology, Inc.");
        cic.put(1262, "Auxivia");
        cic.put(1263, "DaisyWorks, Inc");
        cic.put(1264, "Kosi Limited");
        cic.put(1265, "Theben AG");
        cic.put(1266, "InDreamer Techsol Private Limited");
        cic.put(1267, "Cerevast Medical");
        cic.put(1268, "ZanCompute Inc.");
        cic.put(1269, "Pirelli Tyre S.P.A.");
        cic.put(1270, "McLear Limited");
        cic.put(1271, "Shenzhen Huiding Technology Co.,Ltd.");
        cic.put(1272, "Convergence Systems Limited");
        cic.put(1273, "Interactio");
        cic.put(1274, "Androtec GmbH");
        cic.put(1275, "Benchmark Drives GmbH & Co. KG");
        cic.put(1276, "SwingLync L. L. C.");
        cic.put(1277, "Tapkey GmbH");
        cic.put(1278, "Woosim Systems Inc.");
        cic.put(1279, "Microsemi Corporation");
        cic.put(1280, "Wiliot LTD.");
        cic.put(1281, "Polaris IND");
        cic.put(1282, "Specifi-Kali LLC");
        cic.put(1283, "Locoroll, Inc");
        cic.put(1284, "PHYPLUS Inc");
        cic.put(1285, "Inplay Technologies LLC");
        cic.put(1286, "Hager");
        cic.put(1287, "Yellowcog");
        cic.put(1288, "Axes System sp. z o. o.");
        cic.put(1289, "myLIFTER Inc.");
        cic.put(1290, "Shake-on B.V.");
        cic.put(1291, "Vibrissa Inc.");
        cic.put(1292, "OSRAM GmbH");
        cic.put(1293, "TRSystems GmbH");
        cic.put(1294, "Yichip Microelectronics (Hangzhou) Co.,Ltd.");
        cic.put(1295, "Foundation Engineering LLC");
        cic.put(1296, "UNI-ELECTRONICS, INC.");
        cic.put(1297, "Brookfield Equinox LLC");
        cic.put(1298, "Soprod SA");
        cic.put(1299, "9974091 Canada Inc.");
        cic.put(1300, "FIBRO GmbH");
        cic.put(1301, "RB Controls Co., Ltd.");
        cic.put(1302, "Footmarks");
        cic.put(1303, "Amcore AB");
        cic.put(1304, "MAMORIO.inc");
        cic.put(1305, "Tyto Life LLC");
        cic.put(1306, "Leica Camera AG");
        cic.put(1307, "Angee Technologies Ltd.");
        cic.put(1308, "EDPS");
        cic.put(1309, "OFF Line Co., Ltd.");
        cic.put(1310, "Detect Blue Limited");
        cic.put(1311, "Setec Pty Ltd");
        cic.put(1312, "Target Corporation");
        cic.put(1313, "IAI Corporation");
        cic.put(1314, "NS Tech, Inc.");
        cic.put(1315, "MTG Co., Ltd.");
        cic.put(1316, "Hangzhou iMagic Technology Co., Ltd");
        cic.put(1317, "HONGKONG NANO IC TECHNOLOGIES CO., LIMITED");
        cic.put(1318, "Honeywell International Inc.");
        cic.put(1319, "Albrecht JUNG");
        cic.put(1320, "Lunera Lighting Inc.");
        cic.put(1321, "Lumen UAB");
        cic.put(1322, "Keynes Controls Ltd");
        cic.put(1323, "Novartis AG");
        cic.put(1324, "Geosatis SA");
        cic.put(1325, "EXFO, Inc.");
        cic.put(1326, "LEDVANCE GmbH");
        cic.put(1327, "Center ID Corp.");
        cic.put(1328, "Adolene, Inc.");
        cic.put(1329, "D&M Holdings Inc.");
        cic.put(1330, "CRESCO Wireless, Inc.");
        cic.put(1331, "Nura Operations Pty Ltd");
        cic.put(1332, "Frontiergadget, Inc.");
        cic.put(1333, "Smart Component Technologies Limited");
        cic.put(1334, "ZTR Control Systems LLC");
        cic.put(1335, "MetaLogics Corporation");
        cic.put(1336, "Medela AG");
        cic.put(1337, "OPPLE Lighting Co., Ltd");
        cic.put(1338, "Savitech Corp.,");
        cic.put(1339, "prodigy");
        cic.put(1340, "Screenovate Technologies Ltd");
        cic.put(1341, "TESA SA");
        cic.put(1342, "CLIM8 LIMITED");
        cic.put(1343, "Silergy Corp");
        cic.put(1344, "SilverPlus, Inc");
        cic.put(1345, "Sharknet srl");
        cic.put(1346, "Mist Systems, Inc.");
        cic.put(1347, "MIWA LOCK CO.,Ltd");
        cic.put(1348, "OrthoSensor, Inc.");
        cic.put(1349, "Candy Hoover Group s.r.l");
        cic.put(1350, "Apexar Technologies S.A.");
        cic.put(1351, "LOGICDATA d.o.o.");
        cic.put(1352, "Knick Elektronische Messgeraete GmbH & Co. KG");
        cic.put(1353, "Smart Technologies and Investment Limited");
        cic.put(1354, "Linough Inc.");
        cic.put(1355, "Advanced Electronic Designs, Inc.");
        cic.put(1356, "Carefree Scott Fetzer Co Inc");
        cic.put(1357, "Sensome");
        cic.put(1358, "FORTRONIK storitve d.o.o.");
        cic.put(1359, "Sinnoz");
        cic.put(1360, "Versa Networks, Inc.");
        cic.put(1361, "Sylero");
        cic.put(1362, "Avempace SARL");
        cic.put(1363, "Nintendo Co., Ltd.");
        cic.put(1364, "National Instruments");
        cic.put(1365, "KROHNE Messtechnik GmbH");
        cic.put(1366, "Otodynamics Ltd");
        cic.put(1367, "Arwin Technology Limited");
        cic.put(1368, "benegear, inc.");
        cic.put(1369, "Newcon Optik");
        cic.put(1370, "CANDY HOUSE, Inc.");
        cic.put(1371, "FRANKLIN TECHNOLOGY INC");
        cic.put(1372, "Lely");
        cic.put(1373, "Valve Corporation");
        cic.put(1374, "Hekatron Vertriebs GmbH");
        cic.put(1375, "PROTECH S.A.S. DI GIRARDI ANDREA & C.");
        cic.put(1376, "Sarita CareTech IVS");
        cic.put(1377, "Finder S.p.A.");
        cic.put(1378, "Thalmic Labs Inc.");
        cic.put(1379, "Steinel Vertrieb GmbH");
        cic.put(1380, "Beghelli Spa");
        cic.put(1381, "Beijing Smartspace Technologies Inc.");
        cic.put(1382, "CORE TRANSPORT TECHNOLOGIES NZ LIMITED");
        cic.put(1383, "Xiamen Everesports Goods Co., Ltd");
        cic.put(1384, "Bodyport Inc.");
        cic.put(1385, "Audionics System, INC.");
        cic.put(1386, "Flipnavi Co.,Ltd.");
        cic.put(1387, "Rion Co., Ltd.");
        cic.put(1388, "Long Range Systems, LLC");
        cic.put(1389, "Redmond Industrial Group LLC");
        cic.put(1390, "VIZPIN INC.");
        cic.put(1391, "BikeFinder AS");
        cic.put(1392, "Consumer Sleep Solutions LLC");
        cic.put(1393, "PSIKICK, INC.");
        cic.put(1394, "AntTail.com");
        cic.put(1395, "Lighting Science Group Corp.");
        cic.put(1396, "AFFORDABLE ELECTRONICS INC");
        cic.put(1397, "Integral Memroy Plc");
        cic.put(1398, "Globalstar, Inc.");
        cic.put(1399, "True Wearables, Inc.");
        cic.put(1400, "Wellington Drive Technologies Ltd");
        cic.put(1401, "Ensemble Tech Private Limited");
        cic.put(1402, "OMNI Remotes");
        cic.put(1403, "Duracell U.S. Operations Inc.");
        cic.put(1404, "Toor Technologies LLC");
        cic.put(1405, "Instinct Performance");
        cic.put(1406, "Beco, Inc");
        cic.put(1407, "Scuf Gaming International, LLC");
        cic.put(1408, "ARANZ Medical Limited");
        cic.put(1409, "LYS TECHNOLOGIES LTD");
        cic.put(1410, "Breakwall Analytics, LLC");
        cic.put(1411, "Code Blue Communications");
        cic.put(1412, "Gira Giersiepen GmbH & Co. KG");
        cic.put(1413, "Hearing Lab Technology");
        cic.put(1414, "LEGRAND");
        cic.put(1415, "Derichs GmbH");
        cic.put(1416, "ALT-TEKNIK LLC");
        cic.put(1417, "Star Technologies");
    }

    /**
     * Returns the company name as a String
     *
     * @param id the Bluetooth company identifier
     * @return The company name
     */
    public static @Nullable String get(@Nullable Integer id) {
        if (id != null) {
            return cic.get(id);
        } else {
            return null;
        }
    }
}
