/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.persistence.ui.contentassist

import org.eclipse.smarthome.model.persistence.ui.contentassist.AbstractPersistenceProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PersistenceProposalProvider extends AbstractPersistenceProposalProvider {
}
