/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.script.ui.contentassist

import org.eclipse.smarthome.model.script.ui.contentassist.AbstractScriptProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ScriptProposalProvider extends AbstractScriptProposalProvider {
}
