/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.thing.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ThingUiModule extends org.eclipse.smarthome.model.thing.ui.AbstractThingUiModule {
	public ThingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
