/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.smarthome.model.ide

import com.google.inject.Guice
import org.eclipse.smarthome.model.SitemapRuntimeModule
import org.eclipse.smarthome.model.SitemapStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SitemapIdeSetup extends SitemapStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SitemapRuntimeModule, new SitemapIdeModule))
	}
	
}
