/**
 * Copyright (c) 2014-2016 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.eclipse.smarthome.binding.ble;

import java.util.HashMap;
import java.util.Map;

/**
 * This is a list of known Bluetooth Manufacturers
 *
 * @author Chris Jackson - Initial Contribution
 *
 */
public class BluetoothManufacturer {
    private static final Map<Integer, String> manufacturers = new HashMap<Integer, String>();

    static {
        manufacturers.put(0, "Ericsson Technology Licensing");
        manufacturers.put(1, "Nokia Mobile Phones");
        manufacturers.put(2, "Intel Corp.");
        manufacturers.put(3, "IBM Corp.");
        manufacturers.put(4, "Toshiba Corp.");
        manufacturers.put(5, "3Com");
        manufacturers.put(6, "Microsoft");
        manufacturers.put(7, "Lucent");
        manufacturers.put(8, "Motorola");
        manufacturers.put(9, "Infineon Technologies AG");
        manufacturers.put(10, "Cambridge Silicon Radio");
        manufacturers.put(11, "Silicon Wave");
        manufacturers.put(12, "Digianswer A/S");
        manufacturers.put(13, "Texas Instruments Inc.");
        manufacturers.put(14, "Ceva, Inc. (formerly Parthus Technologies, Inc.)");
        manufacturers.put(15, "Broadcom Corporation");
        manufacturers.put(16, "Mitel Semiconductor");
        manufacturers.put(17, "Widcomm, Inc");
        manufacturers.put(18, "Zeevo, Inc.");
        manufacturers.put(19, "Atmel Corporation");
        manufacturers.put(20, "Mitsubishi Electric Corporation");
        manufacturers.put(21, "RTX Telecom A/S");
        manufacturers.put(22, "KC Technology Inc.");
        manufacturers.put(23, "NewLogic");
        manufacturers.put(24, "Transilica, Inc.");
        manufacturers.put(25, "Rohde & Schwarz GmbH & Co. KG");
        manufacturers.put(26, "TTPCom Limited");
        manufacturers.put(27, "Signia Technologies, Inc.");
        manufacturers.put(28, "Conexant Systems Inc.");
        manufacturers.put(29, "Qualcomm");
        manufacturers.put(30, "Inventel");
        manufacturers.put(31, "AVM Berlin");
        manufacturers.put(32, "BandSpeed, Inc.");
        manufacturers.put(33, "Mansella Ltd");
        manufacturers.put(34, "NEC Corporation");
        manufacturers.put(35, "WavePlus Technology Co., Ltd.");
        manufacturers.put(36, "Alcatel");
        manufacturers.put(37, "NXP Semiconductors (formerly Philips Semiconductors)");
        manufacturers.put(38, "C Technologies");
        manufacturers.put(39, "Open Interface");
        manufacturers.put(40, "R F Micro Devices");
        manufacturers.put(41, "Hitachi Ltd");
        manufacturers.put(42, "Symbol Technologies, Inc.");
        manufacturers.put(43, "Tenovis");
        manufacturers.put(44, "Macronix International Co. Ltd.");
        manufacturers.put(45, "GCT Semiconductor");
        manufacturers.put(46, "Norwood Systems");
        manufacturers.put(47, "MewTel Technology Inc.");
        manufacturers.put(48, "ST Microelectronics");
        manufacturers.put(49, "Synopsis");
        manufacturers.put(50, "Red-M (Communications) Ltd");
        manufacturers.put(51, "Commil Ltd");
        manufacturers.put(52, "Computer Access Technology Corporation (CATC)");
        manufacturers.put(53, "Eclipse (HQ Espana) S.L.");
        manufacturers.put(54, "Renesas Electronics Corporation");
        manufacturers.put(55, "Mobilian Corporation");
        manufacturers.put(56, "Terax");
        manufacturers.put(57, "Integrated System Solution Corp.");
        manufacturers.put(58, "Matsushita Electric Industrial Co., Ltd.");
        manufacturers.put(59, "Gennum Corporation");
        manufacturers.put(60, "BlackBerry Limited (formerly Research In Motion)");
        manufacturers.put(61, "IPextreme, Inc.");
        manufacturers.put(62, "Systems and Chips, Inc.");
        manufacturers.put(63, "Bluetooth SIG, Inc.");
        manufacturers.put(64, "Seiko Epson Corporation");
        manufacturers.put(65, "Integrated Silicon Solution Taiwan, Inc.");
        manufacturers.put(66, "CONWISE Technology Corporation Ltd");
        manufacturers.put(67, "PARROT SA");
        manufacturers.put(68, "Socket Mobile");
        manufacturers.put(69, "Atheros Communications, Inc.");
        manufacturers.put(70, "MediaTek, Inc.");
        manufacturers.put(71, "Bluegiga");
        manufacturers.put(72, "Marvell Technology Group Ltd.");
        manufacturers.put(73, "3DSP Corporation");
        manufacturers.put(74, "Accel Semiconductor Ltd.");
        manufacturers.put(75, "Continental Automotive Systems");
        manufacturers.put(76, "Apple, Inc.");
        manufacturers.put(77, "Staccato Communications, Inc.");
        manufacturers.put(78, "Avago Technologies");
        manufacturers.put(79, "APT Licensing Ltd.");
        manufacturers.put(80, "SiRF Technology");
        manufacturers.put(81, "Tzero Technologies, Inc.");
        manufacturers.put(82, "J&M Corporation");
        manufacturers.put(83, "Free2move AB");
        manufacturers.put(84, "3DiJoy Corporation");
        manufacturers.put(85, "Plantronics, Inc.");
        manufacturers.put(86, "Sony Ericsson Mobile Communications");
        manufacturers.put(87, "Harman International Industries, Inc.");
        manufacturers.put(88, "Vizio, Inc.");
        manufacturers.put(89, "Nordic Semiconductor ASA");
        manufacturers.put(90, "EM Microelectronic-Marin SA");
        manufacturers.put(91, "Ralink Technology Corporation");
        manufacturers.put(92, "Belkin International, Inc.");
        manufacturers.put(93, "Realtek Semiconductor Corporation");
        manufacturers.put(94, "Stonestreet One, LLC");
        manufacturers.put(95, "Wicentric, Inc.");
        manufacturers.put(96, "RivieraWaves S.A.S");
        manufacturers.put(97, "RDA Microelectronics");
        manufacturers.put(98, "Gibson Guitars");
        manufacturers.put(99, "MiCommand Inc.");
        manufacturers.put(100, "Band XI International, LLC");
        manufacturers.put(101, "Hewlett-Packard Company");
        manufacturers.put(102, "9Solutions Oy");
        manufacturers.put(103, "GN Netcom A/S");
        manufacturers.put(104, "General Motors");
        manufacturers.put(105, "A&D Engineering, Inc.");
        manufacturers.put(106, "MindTree Ltd.");
        manufacturers.put(107, "Polar Electro OY");
        manufacturers.put(108, "Beautiful Enterprise Co., Ltd.");
        manufacturers.put(109, "BriarTek, Inc.");
        manufacturers.put(110, "Summit Data Communications, Inc.");
        manufacturers.put(111, "Sound ID");
        manufacturers.put(112, "Monster, LLC");
        manufacturers.put(113, "connectBlue AB");
        manufacturers.put(114, "ShangHai Super Smart Electronics Co. Ltd.");
        manufacturers.put(115, "Group Sense Ltd.");
        manufacturers.put(116, "Zomm, LLC");
        manufacturers.put(117, "Samsung Electronics Co. Ltd.");
        manufacturers.put(118, "Creative Technology Ltd.");
        manufacturers.put(119, "Laird Technologies");
        manufacturers.put(120, "Nike, Inc.");
        manufacturers.put(121, "lesswire AG");
        manufacturers.put(122, "MStar Semiconductor, Inc.");
        manufacturers.put(123, "Hanlynn Technologies");
        manufacturers.put(124, "A & R Cambridge");
        manufacturers.put(125, "Seers Technology Co. Ltd");
        manufacturers.put(126, "Sports Tracking Technologies Ltd.");
        manufacturers.put(127, "Autonet Mobile");
        manufacturers.put(128, "DeLorme Publishing Company, Inc.");
        manufacturers.put(129, "WuXi Vimicro");
        manufacturers.put(130, "Sennheiser Communications A/S");
        manufacturers.put(131, "TimeKeeping Systems, Inc.");
        manufacturers.put(132, "Ludus Helsinki Ltd.");
        manufacturers.put(133, "BlueRadios, Inc.");
        manufacturers.put(134, "equinox AG");
        manufacturers.put(135, "Garmin International, Inc.");
        manufacturers.put(136, "Ecotest");
        manufacturers.put(137, "GN ReSound A/S");
        manufacturers.put(138, "Jawbone");
        manufacturers.put(139, "Topcorn Positioning Systems, LLC");
        manufacturers.put(140, "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)");
        manufacturers.put(141, "Zscan Software");
        manufacturers.put(142, "Quintic Corp.");
        manufacturers.put(143, "Stollman E+V GmbH");
        manufacturers.put(144, "Funai Electric Co., Ltd.");
        manufacturers.put(145, "Advanced PANMOBIL Systems GmbH & Co. KG");
        manufacturers.put(146, "ThinkOptics, Inc.");
        manufacturers.put(147, "Universal Electronics, Inc.");
        manufacturers.put(148, "Airoha Technology Corp.");
        manufacturers.put(149, "NEC Lighting, Ltd.");
        manufacturers.put(150, "ODM Technology, Inc.");
        manufacturers.put(151, "ConnecteDevice Ltd.");
        manufacturers.put(152, "zer01.tv GmbH");
        manufacturers.put(153, "i.Tech Dynamic Global Distribution Ltd.");
        manufacturers.put(154, "Alpwise");
        manufacturers.put(155, "Jiangsu Toppower Automotive Electronics Co., Ltd.");
        manufacturers.put(156, "Colorfy, Inc.");
        manufacturers.put(157, "Geoforce Inc.");
        manufacturers.put(158, "Bose Corporation");
        manufacturers.put(159, "Suunto Oy");
        manufacturers.put(160, "Kensington Computer Products Group");
        manufacturers.put(161, "SR-Medizinelektronik");
        manufacturers.put(162, "Vertu Corporation Limited");
        manufacturers.put(163, "Meta Watch Ltd.");
        manufacturers.put(164, "LINAK A/S");
        manufacturers.put(165, "OTL Dynamics LLC");
        manufacturers.put(166, "Panda Ocean Inc.");
        manufacturers.put(167, "Visteon Corporation");
        manufacturers.put(168, "ARP Devices Limited");
        manufacturers.put(169, "Magneti Marelli S.p.A");
        manufacturers.put(170, "CAEN RFID srl");
        manufacturers.put(171, "Ingenieur-Systemgruppe Zahn GmbH");
        manufacturers.put(172, "Green Throttle Games");
        manufacturers.put(173, "Peter Systemtechnik GmbH");
        manufacturers.put(174, "Omegawave Oy");
        manufacturers.put(175, "Cinetix");
        manufacturers.put(176, "Passif Semiconductor Corp");
        manufacturers.put(177, "Saris Cycling Group, Inc");
        manufacturers.put(178, "Bekey A/S");
        manufacturers.put(179, "Clarinox Technologies Pty. Ltd.");
        manufacturers.put(180, "BDE Technology Co., Ltd.");
        manufacturers.put(181, "Swirl Networks");
        manufacturers.put(182, "Meso international");
        manufacturers.put(183, "TreLab Ltd");
        manufacturers.put(184, "Qualcomm Innovation Center, Inc. (QuIC)");
        manufacturers.put(185, "Johnson Controls, Inc.");
        manufacturers.put(186, "Starkey Laboratories Inc.");
        manufacturers.put(187, "S-Power Electronics Limited");
        manufacturers.put(188, "Ace Sensor Inc");
        manufacturers.put(189, "Aplix Corporation");
        manufacturers.put(190, "AAMP of America");
        manufacturers.put(191, "Stalmart Technology Limited");
        manufacturers.put(192, "AMICCOM Electronics Corporation");
        manufacturers.put(193, "Shenzhen Excelsecu Data Technology Co.,Ltd");
        manufacturers.put(194, "Geneq Inc.");
        manufacturers.put(195, "adidas AG");
        manufacturers.put(196, "LG Electronics");
        manufacturers.put(197, "Onset Computer Corporation");
        manufacturers.put(198, "Selfly BV");
        manufacturers.put(199, "Quuppa Oy.");
        manufacturers.put(200, "GeLo Inc");
        manufacturers.put(201, "Evluma");
        manufacturers.put(202, "MC10");
        manufacturers.put(203, "Binauric SE");
        manufacturers.put(204, "Beats Electronics");
        manufacturers.put(205, "Microchip Technology Inc.");
        manufacturers.put(206, "Elgato Systems GmbH");
        manufacturers.put(207, "ARCHOS SA");
        manufacturers.put(208, "Dexcom, Inc.");
        manufacturers.put(209, "Polar Electro Europe B.V.");
        manufacturers.put(210, "Dialog Semiconductor B.V.");
        manufacturers.put(211, "Taixingbang Technology (HK) Co,. LTD.");
        manufacturers.put(212, "Kawantech");
        manufacturers.put(213, "Austco Communication Systems");
        manufacturers.put(214, "Timex Group USA, Inc.");
        manufacturers.put(215, "Qualcomm Technologies, Inc.");
        manufacturers.put(216, "Qualcomm Connected Experiences, Inc.");
        manufacturers.put(217, "Voyetra Turtle Beach");
        manufacturers.put(218, "txtr GmbH");
        manufacturers.put(219, "Biosentronics");
        manufacturers.put(220, "Procter & Gamble");
        manufacturers.put(221, "Hosiden Corporation");
        manufacturers.put(222, "Muzik LLC");
        manufacturers.put(223, "Misfit Wearables Corp");
        manufacturers.put(224, "Google");
        manufacturers.put(225, "Danlers Ltd");
        manufacturers.put(226, "Semilink Inc");
        manufacturers.put(227, "inMusic Brands, Inc");
        manufacturers.put(228, "L.S. Research Inc.");
        manufacturers.put(229, "Eden Software Consultants Ltd.");
        manufacturers.put(230, "Freshtemp");
        manufacturers.put(231, "KS Technologies");
        manufacturers.put(232, "ACTS Technologies");
        manufacturers.put(233, "Vtrack Systems");
        manufacturers.put(234, "Nielsen-Kellerman Company");
        manufacturers.put(235, "Server Technology, Inc.");
        manufacturers.put(236, "BioResearch Associates");
        manufacturers.put(237, "Jolly Logic, LLC");
        manufacturers.put(238, "Above Average Outcomes, Inc.");
        manufacturers.put(239, "Bitsplitters GmbH");
        manufacturers.put(240, "PayPal, Inc.");
        manufacturers.put(241, "Witron Technology Limited");
        manufacturers.put(242, "Aether Things Inc. (formerly Morse Project Inc.)");
        manufacturers.put(243, "Kent Displays Inc.");
        manufacturers.put(244, "Nautilus Inc .");
        manufacturers.put(245, "Smartifier Oy");
        manufacturers.put(246, "Elcometer Limited");
        manufacturers.put(247, "VSN Technologies Inc.");
        manufacturers.put(248, "AceUni Corp., Ltd.");
        manufacturers.put(249, "StickNFind");
        manufacturers.put(250, "Crystal Code AB");
        manufacturers.put(251, "KOUKAAM a.s.");
        manufacturers.put(252, "Delphi Corporation");
        manufacturers.put(253, "ValenceTech Limited");
        manufacturers.put(254, "Reserved");
        manufacturers.put(255, "Typo Products, LLC");
        manufacturers.put(256, "TomTom International BV");
        manufacturers.put(257, "Fugoo, Inc");
        manufacturers.put(258, "Keiser Corporation");
        manufacturers.put(259, "Bang & Olufsen A/S");
        manufacturers.put(260, "PLUS Locations Systems Pty Ltd");
        manufacturers.put(261, "Ubiquitous Computing Technology Corporation");
        manufacturers.put(262, "Innovative Yachtter Solutions");
        manufacturers.put(263, "William Demant Holding A/S");
        manufacturers.put(264, "Chicony Electronics Co., Ltd.");
        manufacturers.put(265, "Atus BV");
        manufacturers.put(266, "Codegate Ltd.");
        manufacturers.put(267, "ERi, Inc.");
        manufacturers.put(268, "Transducers Direct, LLC");
        manufacturers.put(269, "Fujitsu Ten Limited");
        manufacturers.put(270, "Audi AG");
        manufacturers.put(271, "HiSilicon Technologies Co., Ltd.");
        manufacturers.put(272, "Nippon Seiki Co., Ltd.");
        manufacturers.put(273, "Steelseries ApS");
        manufacturers.put(274, "Visybl Inc.");
        manufacturers.put(275, "Openbrain Technologies, Co., Ltd.");
        manufacturers.put(276, "Xensr");
        manufacturers.put(277, "e.solutions");
        manufacturers.put(278, "1OAK Technologies");
        manufacturers.put(279, "Wimoto Technologies Inc");
        manufacturers.put(280, "Radius Networks, Inc.");
        manufacturers.put(281, "Wize Technology Co., Ltd.");
        manufacturers.put(282, "Qualcomm Labs, Inc.");
        manufacturers.put(283, "Aruba Networks");
        manufacturers.put(284, "Baidu");
        manufacturers.put(285, "Arendi AG");
        manufacturers.put(286, "Skoda Auto a.s.");
        manufacturers.put(287, "Volkswagon AG");
        manufacturers.put(288, "Porsche AG");
        manufacturers.put(289, "Sino Wealth Electronic Ltd.");
        manufacturers.put(290, "AirTurn, Inc.");
        manufacturers.put(291, "Kinsa, Inc.");
        manufacturers.put(292, "HID Global");
        manufacturers.put(293, "SEAT es");
        manufacturers.put(294, "Promethean Ltd.");
        manufacturers.put(295, "Salutica Allied Solutions");
        manufacturers.put(296, "GPSI Group Pty Ltd");
        manufacturers.put(297, "Nimble Devices Oy");
        manufacturers.put(298, "Changzhou Yongse Infotech Co., Ltd");
        manufacturers.put(299, "SportIQ");
        manufacturers.put(300, "TEMEC Instruments B.V.");
        manufacturers.put(301, "Sony Corporation");
        manufacturers.put(302, "ASSA ABLOY");
        manufacturers.put(303, "Clarion Co., Ltd.");
        manufacturers.put(304, "Warehouse Innovations");
        manufacturers.put(305, "Cypress Semiconductor Corporation");
        manufacturers.put(306, "MADS Inc");
        manufacturers.put(307, "Blue Maestro Limited");
        manufacturers.put(308, "Resolution Products, Inc.");
        manufacturers.put(309, "Airewear LLC");
        manufacturers.put(310, "Seed Labs, Inc. (formerly ETC sp. z.o.o.)");
        manufacturers.put(311, "Prestigio Plaza Ltd.");
        manufacturers.put(312, "NTEO Inc.");
        manufacturers.put(313, "Focus Systems Corporation");
        manufacturers.put(314, "Tencent Holdings Limited");
        manufacturers.put(315, "Allegion");
        manufacturers.put(316, "Murata Manufacuring Co., Ltd.");
        manufacturers.put(318, "Nod, Inc.");
        manufacturers.put(319, "B&B Manufacturing Company");
        manufacturers.put(320, "Alpine Electronics (China) Co., Ltd");
        manufacturers.put(321, "FedEx Services");
        manufacturers.put(322, "Grape Systems Inc.");
        manufacturers.put(323, "Bkon Connect");
        manufacturers.put(324, "Lintech GmbH");
        manufacturers.put(325, "Novatel Wireless");
        manufacturers.put(326, "Ciright");
        manufacturers.put(327, "Mighty Cast, Inc.");
        manufacturers.put(328, "Ambimat Electronics");
        manufacturers.put(329, "Perytons Ltd.");
        manufacturers.put(330, "Tivoli Audio, LLC");
        manufacturers.put(331, "Master Lock");
        manufacturers.put(332, "Mesh-Net Ltd");
        manufacturers.put(333, "Huizhou Desay SV Automotive CO., LTD.");
        manufacturers.put(334, "Tangerine, Inc.");
        manufacturers.put(335, "B&W Group Ltd.");
        manufacturers.put(336, "Pioneer Corporation");
        manufacturers.put(337, "OnBeep");
        manufacturers.put(338, "Vernier Software & Technology");
        manufacturers.put(339, "ROL Ergo");
        manufacturers.put(340, "Pebble Technology");
        manufacturers.put(341, "NETATMO");
        manufacturers.put(342, "Accumulate AB");
        manufacturers.put(343, "Anhui Huami Information Technology Co., Ltd.");
        manufacturers.put(344, "Inmite s.r.o.");
        manufacturers.put(345, "ChefSteps, Inc.");
        manufacturers.put(346, "micas AG");
        manufacturers.put(347, "Biomedical Research Ltd.");
        manufacturers.put(348, "Pitius Tec S.L.");
        manufacturers.put(349, "Estimote, Inc.");
        manufacturers.put(350, "Unikey Technologies, Inc.");
        manufacturers.put(351, "Timer Cap Co.");
        manufacturers.put(352, "AwoX");
        manufacturers.put(353, "yikes");
        manufacturers.put(354, "MADSGlobal NZ Ltd.");
        manufacturers.put(355, "PCH International");
        manufacturers.put(356, "Qingdao Yeelink Information Technology Co., Ltd.");
        manufacturers.put(357, "Milwaukee Tool (formerly Milwaukee Electric Tools)");
        manufacturers.put(358, "MISHIK Pte Ltd");
        manufacturers.put(359, "Bayer HealthCare");
        manufacturers.put(360, "Spicebox LLC");
        manufacturers.put(361, "emberlight");
        manufacturers.put(362, "Cooper-Atkins Corporation");
        manufacturers.put(363, "Qblinks");
        manufacturers.put(364, "MYSPHERA");
        manufacturers.put(365, "LifeScan Inc");
        manufacturers.put(366, "Volantic AB");
        manufacturers.put(367, "Podo Labs, Inc");
        manufacturers.put(368, "Roche Diabetes Care AG");
        manufacturers.put(369, "Amazon Fulfillment Service");
        manufacturers.put(370, "Connovate Technology Private Limited");
        manufacturers.put(371, "Kocomojo, LLC");
        manufacturers.put(372, "Everykey LLC");
        manufacturers.put(373, "Dynamic Controls");
        manufacturers.put(374, "SentriLock");
        manufacturers.put(375, "I-SYST inc.");
        manufacturers.put(376, "CASIO COMPUTER CO., LTD.");
        manufacturers.put(377, "LAPIS Semiconductor Co., Ltd.");
        manufacturers.put(378, "Telemonitor, Inc.");
        manufacturers.put(379, "taskit GmbH");
        manufacturers.put(380, "Daimler AG");
        manufacturers.put(381, "BatAndCat");
        manufacturers.put(382, "BluDotz Ltd");
        manufacturers.put(383, "XTel ApS");
        manufacturers.put(384, "Gigaset Communications GmbH");
        manufacturers.put(385, "Gecko Health Innovations, Inc.");
        manufacturers.put(386, "HOP Ubiquitous");
        manufacturers.put(387, "To Be Assigned");
        manufacturers.put(388, "Nectar");
        manufacturers.put(389, "bel'apps LLC");
        manufacturers.put(390, "CORE Lighting Ltd");
        manufacturers.put(391, "Seraphim Sense Ltd");
        manufacturers.put(392, "Unico RBC");
        manufacturers.put(393, "Physical Enterprises Inc.");
        manufacturers.put(394, "Able Trend Technology Limited");
        manufacturers.put(395, "Konica Minolta, Inc.");
        manufacturers.put(396, "Wilo SE");
        manufacturers.put(397, "Extron Design Services");
        manufacturers.put(398, "Fitbit, Inc.");
        manufacturers.put(399, "Fireflies Systems");
        manufacturers.put(400, "Intelletto Technologies Inc.");
        manufacturers.put(401, "FDK CORPORATION");
        manufacturers.put(402, "Cloudleaf, Inc");
        manufacturers.put(403, "Maveric Automation LLC");
        manufacturers.put(404, "Acoustic Stream Corporation");
        manufacturers.put(405, "Zuli");
        manufacturers.put(406, "Paxton Access Ltd");
        manufacturers.put(407, "WiSilica Inc");
        manufacturers.put(408, "Vengit Limited");
        manufacturers.put(409, "SALTO SYSTEMS S.L.");
        manufacturers.put(410, "TRON Forum (formerly T-Engine Forum)");
        manufacturers.put(411, "CUBETECH s.r.o.");
        manufacturers.put(412, "Cokiya Incorporated");
        manufacturers.put(413, "CVS Health");
        manufacturers.put(414, "Ceruus");
        manufacturers.put(415, "Strainstall Ltd");
        manufacturers.put(416, "Channel Enterprises (HK) Ltd.");
        manufacturers.put(417, "FIAMM");
        manufacturers.put(418, "GIGALANE.CO.,LTD");
        manufacturers.put(419, "EROAD");
        manufacturers.put(420, "Mine Safety Appliances");
        manufacturers.put(421, "Icon Health and Fitness");
        manufacturers.put(422, "Asandoo GmbH");
        manufacturers.put(423, "ENERGOUS CORPORATION");
        manufacturers.put(424, "Taobao");
        manufacturers.put(425, "Canon Inc.");
        manufacturers.put(426, "Geophysical Technology Inc.");
        manufacturers.put(427, "Facebook, Inc.");
        manufacturers.put(428, "Nipro Diagnostics, Inc.");
        manufacturers.put(429, "FlightSafety International");
        manufacturers.put(430, "Earlens Corporation");
        manufacturers.put(431, "Sunrise Micro Devices, Inc.");
        manufacturers.put(432, "Star Micronics Co., Ltd.");
        manufacturers.put(433, "Netizens Sp. z o.o.");
        manufacturers.put(434, "Nymi Inc.");
        manufacturers.put(435, "Nytec, Inc.");
        manufacturers.put(436, "Trineo Sp. z o.o.");
        manufacturers.put(437, "Nest Labs Inc.");
        manufacturers.put(438, "LM Technologies Ltd");
        manufacturers.put(439, "General Electric Company");
        manufacturers.put(440, "i+D3 S.L.");
        manufacturers.put(441, "HANA Micron");
        manufacturers.put(442, "Stages Cycling LLC");
        manufacturers.put(443, "Cochlear Bone Anchored Solutions AB");
        manufacturers.put(444, "SenionLab AB");
        manufacturers.put(445, "Syszone Co., Ltd");
        manufacturers.put(446, "Pulsate Mobile Ltd.");
        manufacturers.put(447, "Hong Kong HunterSun Electronic Limited");
        manufacturers.put(448, "pironex GmbH");
        manufacturers.put(449, "BRADATECH Corp.");
        manufacturers.put(450, "Transenergooil AG");
        manufacturers.put(451, "Bunch");
        manufacturers.put(452, "DME Microelectronics");
        manufacturers.put(453, "Bitcraze AB");
        manufacturers.put(454, "HASWARE Inc.");
        manufacturers.put(455, "Abiogenix Inc.");
        manufacturers.put(456, "Poly-Control ApS");
        manufacturers.put(457, "Avi-on");
        manufacturers.put(458, "Laerdal Medical AS");
        manufacturers.put(459, "Fetch My Pet");
        manufacturers.put(460, "Sam Labs Ltd.");
        manufacturers.put(461, "Chengdu Synwing Technology Ltd");
        manufacturers.put(462, "HOUWA SYSTEM DESIGN, k.k.");
        manufacturers.put(463, "BSH");
        manufacturers.put(464, "Primus Inter Pares Ltd");
        manufacturers.put(465, "August");
        manufacturers.put(466, "Gill Electronics");
        manufacturers.put(467, "Sky Wave Design");
        manufacturers.put(468, "Newlab S.r.l.");
        manufacturers.put(469, "ELAD srl");
        manufacturers.put(470, "G-wearables inc.");
        manufacturers.put(471, "Squadrone Systems Inc.");
        manufacturers.put(472, "Code Corporation");
        manufacturers.put(473, "Savant Systems LLC");
        manufacturers.put(474, "Logitech International SA");
        manufacturers.put(475, "Innblue Consulting");
        manufacturers.put(476, "iParking Ltd.");
        manufacturers.put(477, "Koninklijke Philips Electronics N.V.");
        manufacturers.put(478, "Minelab Electronics Pty Limited");
        manufacturers.put(479, "Bison Group Ltd.");
        manufacturers.put(480, "Widex A/S");
        manufacturers.put(481, "Jolla Ltd");
        manufacturers.put(482, "Lectronix, Inc.");
        manufacturers.put(483, "Caterpillar Inc");
        manufacturers.put(484, "Freedom Innovations");
        manufacturers.put(485, "Dynamic Devices Ltd");
        manufacturers.put(486, "Technology Solutions (UK) Ltd");
        manufacturers.put(487, "IPS Group Inc.");
        manufacturers.put(488, "STIR");
        manufacturers.put(489, "Sano, Inc");
        manufacturers.put(490, "Advanced Application Design, Inc.");
        manufacturers.put(491, "AutoMap LLC");
        manufacturers.put(492, "Spreadtrum Communications Shanghai Ltd");
        manufacturers.put(493, "CuteCircuit LTD");
        manufacturers.put(494, "Valeo Service");
        manufacturers.put(495, "Fullpower Technologies, Inc.");
        manufacturers.put(496, "KloudNation");
        manufacturers.put(497, "Zebra Technologies Corporation");
        manufacturers.put(498, "Itron, Inc.");
        manufacturers.put(499, "The University of Tokyo");
        manufacturers.put(500, "UTC Fire and Security");
        manufacturers.put(501, "Cool Webthings Limited");
        manufacturers.put(502, "DJO Global");
        manufacturers.put(503, "Gelliner Limited");
        manufacturers.put(504, "Anyka (Guangzhou) Microelectronics Technology Co, LTD");
        manufacturers.put(505, "Medtronic, Inc.");
        manufacturers.put(506, "Gozio, Inc.");
        manufacturers.put(507, "Form Lifting, LLC");
        manufacturers.put(508, "Wahoo Fitness, LLC");
        manufacturers.put(509, "Kontakt Micro-Location Sp. z o.o.");
        manufacturers.put(510, "Radio System Corporation");
        manufacturers.put(511, "Freescale Semiconductor, Inc.");
        manufacturers.put(512, "Verifone Systems PTe Ltd. Taiwan Branch");
        manufacturers.put(513, "AR Timing");
        manufacturers.put(514, "Rigado LLC");
        manufacturers.put(515, "Kemppi Oy");
        manufacturers.put(516, "Tapcentive Inc.");
        manufacturers.put(517, "Smartbotics Inc.");
        manufacturers.put(518, "Otter Products, LLC");
        manufacturers.put(519, "STEMP Inc.");
        manufacturers.put(520, "LumiGeek LLC");
        manufacturers.put(521, "InvisionHeart Inc.");
        manufacturers.put(522, "Macnica Inc.");
        manufacturers.put(523, "Jaguar Land Rover Limited");
        manufacturers.put(524, "CoroWare Technologies, Inc");
        manufacturers.put(525, "Simplo Technology Co., LTD");
        manufacturers.put(526, "Omron Healthcare Co., LTD");
        manufacturers.put(527, "Comodule GMBH");
        manufacturers.put(528, "ikeGPS");
        manufacturers.put(529, "Telink Semiconductor Co. Ltd");
        manufacturers.put(530, "Interplan Co., Ltd");
        manufacturers.put(531, "Wyler AG");
        manufacturers.put(532, "IK Multimedia Production srl");
        manufacturers.put(533, "Lukoton Experience Oy");
        manufacturers.put(534, "MTI Ltd");
        manufacturers.put(535, "Tech4home, Lda");
        manufacturers.put(536, "Hiotech AB");
        manufacturers.put(537, "DOTT Limited");
        manufacturers.put(538, "Blue Speck Labs, LLC");
        manufacturers.put(539, "Cisco Systems Inc");
        manufacturers.put(540, "Mobicomm Inc");
        manufacturers.put(541, "Edamic");
        manufacturers.put(542, "Goodnet Ltd");
        manufacturers.put(543, "Luster Leaf Products Inc");
        manufacturers.put(544, "Manus Machina BV");
        manufacturers.put(545, "Mobiquity Networks Inc");
        manufacturers.put(546, "Praxis Dynamics");
        manufacturers.put(547, "Philip Morris Products S.A.");
        manufacturers.put(548, "Comarch SA");
        manufacturers.put(549, "Nestlé Nespresso S.A.");
        manufacturers.put(550, "Merlinia A/S");
        manufacturers.put(551, "LifeBEAM Technologies");
        manufacturers.put(552, "Twocanoes Labs, LLC");
        manufacturers.put(553, "Muoverti Limited");
        manufacturers.put(554, "Stamer Musikanlagen GMBH");
        manufacturers.put(555, "Tesla Motors");
        manufacturers.put(556, "Pharynks Corporation");
        manufacturers.put(557, "Lupine");
        manufacturers.put(558, "Siemens AG");
        manufacturers.put(559, "Huami (Shanghai) Culture Communication CO., LTD");
        manufacturers.put(560, "Foster Electric Company, Ltd");
        manufacturers.put(561, "ETA SA");
        manufacturers.put(562, "x-Senso Solutions Kft");
        manufacturers.put(563, "Shenzhen SuLong Communication Ltd");
        manufacturers.put(564, "FengFan (BeiJing) Technology Co, Ltd");
        manufacturers.put(565, "Qrio Inc");
        manufacturers.put(566, "Pitpatpet Ltd");
        manufacturers.put(567, "MSHeli s.r.l.");
        manufacturers.put(568, "Trakm8 Ltd");
        manufacturers.put(569, "JIN CO, Ltd");
        manufacturers.put(570, "Alatech Technology");
        manufacturers.put(571, "Beijing CarePulse Electronic Technology Co, Ltd");
        manufacturers.put(572, "Awarepoint");
        manufacturers.put(573, "ViCentra B.V.");
        manufacturers.put(574, "Raven Industries");
        manufacturers.put(575, "WaveWare Technologies");
        manufacturers.put(576, "Argenox Technologies");
        manufacturers.put(577, "Bragi GmbH");
        manufacturers.put(578, "16Lab Inc");
        manufacturers.put(579, "Masimo Corp");
        manufacturers.put(580, "Iotera Inc.");
        manufacturers.put(581, "Endress+Hauser");
        manufacturers.put(582, "ACKme Networks, Inc.");
        manufacturers.put(583, "FiftyThree Inc.");
        manufacturers.put(584, "Parker Hannifin Corp");
        manufacturers.put(585, "Transcranial Ltd");
        manufacturers.put(586, "Uwatec AG");
        manufacturers.put(587, "Orlan LLC");
        manufacturers.put(588, "Blue Clover Devices");
        manufacturers.put(589, "M-Way Solutions GmbH");
        manufacturers.put(590, "Microtronics Engineering GmbH");
        manufacturers.put(591, "Schneider Schreibgeräte GmbH");
        manufacturers.put(592, "Sapphire Circuits LLC");
        manufacturers.put(593, "Lumo Bodytech Inc.");
        manufacturers.put(594, "UKC Technosolution");
        manufacturers.put(595, "Xicato Inc.");
        manufacturers.put(596, "Playbrush");
        manufacturers.put(597, "Dai Nippon Printing Co., Ltd.");
        manufacturers.put(598, "G24 Power Limited");
        manufacturers.put(599, "AdBabble Local Commerce Inc.");
        manufacturers.put(600, "Devialet SA");
        manufacturers.put(601, "ALTYOR");
        manufacturers.put(602, "University of Applied Sciences Valais/Haute Ecole Valaisanne");
        manufacturers.put(603, "Five Interactive, LLC dba Zendo");
        manufacturers.put(604, "NetEase (Hangzhou) Network co.Ltd.");
        manufacturers.put(605, "Lexmark International Inc.");
        manufacturers.put(606, "Fluke Corporation");
        manufacturers.put(607, "Yardarm Technologies");
        manufacturers.put(608, "SensaRx");
        manufacturers.put(609, "SECVRE GmbH");
        manufacturers.put(610, "Glacial Ridge Technologies");
        manufacturers.put(611, "Identiv, Inc.");
        manufacturers.put(612, "DDS, Inc.");
        manufacturers.put(613, "SMK Corporation");
        manufacturers.put(614, "Schawbel Technologies LLC");
        manufacturers.put(615, "XMI Systems SA");
        manufacturers.put(616, "Cerevo");
        manufacturers.put(617, "Torrox GmbH & Co KG");
        manufacturers.put(618, "Gemalto");
        manufacturers.put(619, "DEKA Research & Development Corp.");
        manufacturers.put(620, "Domster Tadeusz Szydlowski");
        manufacturers.put(621, "Technogym SPA");
        manufacturers.put(622, "FLEURBAEY BVBA");
        manufacturers.put(623, "Aptcode Solutions");
        manufacturers.put(624, "LSI ADL Technology");
        manufacturers.put(625, "Animas Corp");
        manufacturers.put(626, "Alps Electric Co., Ltd.");
        manufacturers.put(627, "OCEASOFT");
        manufacturers.put(628, "Motsai Research");
        manufacturers.put(629, "Geotab");
        manufacturers.put(630, "E.G.O. Elektro-Gerätebau GmbH");
        manufacturers.put(631, "bewhere inc");
        manufacturers.put(632, "Johnson Outdoors Inc");
        manufacturers.put(633, "steute Schaltgerate GmbH & Co. KG");
        manufacturers.put(634, "Ekomini in c.");
        manufacturers.put(635, "DEFA AS");
        manufacturers.put(636, "Aseptika Ltd");
        manufacturers.put(637, "HUAWEI Technologies Co., Ltd. ( 华为技术有限公司 )");
        manufacturers.put(638, "HabitAware, LLC");
        manufacturers.put(639, "ruwido austria gmbh");
        manufacturers.put(640, "ITEC corporation");
        manufacturers.put(641, "StoneL");
        manufacturers.put(642, "Sonova AG");
        manufacturers.put(643, "Maven Machines, Inc.");
        manufacturers.put(644, "Synapse Electronics");
        manufacturers.put(645, "Standard Innovation Inc.");
        manufacturers.put(646, "RF Code, Inc.");
        manufacturers.put(647, "Wally Ventures S.L.");
        manufacturers.put(648, "Willowbank Electronics Ltd");
        manufacturers.put(649, "SK Telecom");
        manufacturers.put(650, "Jetro AS");
        manufacturers.put(651, "Code Gears LTD");
        manufacturers.put(652, "NANOLINK APS");
        manufacturers.put(653, "IF, LLC");
        manufacturers.put(654, "RF Digital Corp");
        manufacturers.put(655, "Church & Dwight Co., Inc");
        manufacturers.put(656, "Multibit Oy");
        manufacturers.put(657, "CliniCloud Inc");
        manufacturers.put(658, "SwiftSensors");
        manufacturers.put(659, "Blue Bite");
        manufacturers.put(660, "ELIAS GmbH");
        manufacturers.put(661, "Sivantos GmbH");
        manufacturers.put(662, "Petzl");
        manufacturers.put(663, "storm power ltd");
        manufacturers.put(664, "EISST Ltd");
        manufacturers.put(665, "Inexess Technology Simma KG");
        manufacturers.put(666, "Currant, Inc.");
        manufacturers.put(667, "C2 Development, Inc.");
        manufacturers.put(668, "Blue Sky Scientific, LLC");
        manufacturers.put(669, "ALOTTAZS LABS, LLC");
        manufacturers.put(670, "Kupson spol. s r.o.");
        manufacturers.put(671, "Areus Engineering GmbH");
        manufacturers.put(672, "Impossible Camera GmbH");
        manufacturers.put(673, "InventureTrack Systems");
        manufacturers.put(674, "LockedUp");
        manufacturers.put(675, "Itude");
        manufacturers.put(676, "Pacific Lock Company");
        manufacturers.put(677, "Tendyron Corporation ( 天地融科技股份有限公司 )");
        manufacturers.put(678, "Robert Bosch GmbH");
        manufacturers.put(679, "Illuxtron international B.V.");
        manufacturers.put(680, "miSport Ltd.");
        manufacturers.put(681, "Chargelib");
        manufacturers.put(682, "Doppler Lab");
        manufacturers.put(683, "BBPOS Limited");
        manufacturers.put(684, "RTB Elektronik GmbH & Co. KG");
        manufacturers.put(685, "Rx Networks, Inc.");
        manufacturers.put(686, "WeatherFlow, Inc.");
        manufacturers.put(687, "Technicolor USA Inc.");
        manufacturers.put(688, "Bestechnic(Shanghai),Ltd");
        manufacturers.put(689, "Raden Inc");
        manufacturers.put(690, "JouZen Oy");
        manufacturers.put(691, "CLABER S.P.A.");
        manufacturers.put(692, "Hyginex, Inc.");
        manufacturers.put(693, "HANSHIN ELECTRIC RAILWAY CO.,LTD.");
        manufacturers.put(694, "Schneider Electric");
        manufacturers.put(695, "Oort Technologies LLC");
        manufacturers.put(696, "Chrono Therapeutics");
        manufacturers.put(697, "Rinnai Corporation");
        manufacturers.put(698, "Swissprime Technologies AG");
        manufacturers.put(699, "Koha.,Co.Ltd");
        manufacturers.put(700, "Genevac Ltd");
        manufacturers.put(701, "Chemtronics");
        manufacturers.put(702, "Seguro Technology Sp. z o.o.");
        manufacturers.put(703, "Redbird Flight Simulations");
        manufacturers.put(704, "Dash Robotics");
        manufacturers.put(705, "LINE Corporation");
        manufacturers.put(706, "Guillemot Corporation");
        manufacturers.put(707, "Techtronic Power Tools Technology Limited");
        manufacturers.put(708, "Wilson Sporting Goods");
        manufacturers.put(709, "Lenovo (Singapore) Pte Ltd. ( )");
        manufacturers.put(710, "Ayatan Sensors");
        manufacturers.put(711, "Electronics Tomorrow Limited");
        manufacturers.put(712, "VASCO Data Security International, Inc.");
        manufacturers.put(713, "PayRange Inc.");
        manufacturers.put(714, "ABOV Semiconductor");
        manufacturers.put(715, "AINA-Wireless Inc.");
        manufacturers.put(716, "Eijkelkamp Soil & Water");
        manufacturers.put(717, "BMA ergonomics b.v.");
        manufacturers.put(718, "Teva Branded Pharmaceutical Products R&D, Inc.");
        manufacturers.put(719, "Anima");
        manufacturers.put(720, "3M");
        manufacturers.put(721, "Empatica Srl");
        manufacturers.put(722, "Afero, Inc.");
        manufacturers.put(723, "Powercast Corporation");
        manufacturers.put(724, "Secuyou ApS");
        manufacturers.put(725, "OMRON Corporation");
        manufacturers.put(726, "Send Solutions");
        manufacturers.put(727, "NIPPON SYSTEMWARE CO.,LTD.");
        manufacturers.put(728, "Neosfar");
        manufacturers.put(729, "Fliegl Agrartechnik GmbH");
        manufacturers.put(730, "Gilvader");
        manufacturers.put(731, "Digi International Inc (R)");
        manufacturers.put(732, "DeWalch Technologies, Inc.");
        manufacturers.put(733, "Flint Rehabilitation Devices, LLC");
        manufacturers.put(734, "Samsung SDS Co., Ltd.");
        manufacturers.put(735, "Blur Product Development");
        manufacturers.put(736, "University of Michigan");
        manufacturers.put(737, "Victron Energy BV");
        manufacturers.put(738, "NTT docomo");
        manufacturers.put(739, "Carmanah Technologies Corp.");
        manufacturers.put(740, "Bytestorm Ltd.");
        manufacturers.put(741, "Espressif Incorporated ( () )");
        manufacturers.put(742, "Unwire");
        manufacturers.put(743, "Connected Yard, Inc.");
        manufacturers.put(744, "American Music Environments");
        manufacturers.put(745, "Sensogram Technologies, Inc.");
        manufacturers.put(746, "Fujitsu Limited");
        manufacturers.put(747, "Ardic Technology");
        manufacturers.put(748, "Delta Systems, Inc");
        manufacturers.put(749, "HTC Corporation");
        manufacturers.put(750, "Citizen Holdings Co., Ltd.");
        manufacturers.put(751, "SMART-INNOVATION.inc");
        manufacturers.put(752, "Blackrat Software");
        manufacturers.put(753, "The Idea Cave, LLC");
        manufacturers.put(754, "GoPro, Inc.");
        manufacturers.put(755, "AuthAir, Inc");
        manufacturers.put(756, "Vensi, Inc.");
        manufacturers.put(757, "Indagem Tech LLC");
        manufacturers.put(758, "Intemo Technologies");
        manufacturers.put(759, "DreamVisions co., Ltd.");
        manufacturers.put(760, "Runteq Oy Ltd");
        manufacturers.put(761, "IMAGINATION TECHNOLOGIES LTD");
        manufacturers.put(762, "CoSTAR TEchnologies");
        manufacturers.put(763, "Clarius Mobile Health Corp.");
        manufacturers.put(764, "Shanghai Frequen Microelectronics Co., Ltd.");
        manufacturers.put(765, "Uwanna, Inc.");
        manufacturers.put(766, "Lierda Science & Technology Group Co., Ltd.");
        manufacturers.put(767, "Silicon Laboratories");
        manufacturers.put(768, "World Moto Inc.");
        manufacturers.put(769, "Giatec Scientific Inc.");
        manufacturers.put(770, "Loop Devices, Inc");
        manufacturers.put(771, "IACA electronique");
        manufacturers.put(772, "Martians Inc");
        manufacturers.put(773, "Swipp ApS");
        manufacturers.put(774, "Life Laboratory Inc.");
        manufacturers.put(775, "FUJI INDUSTRIAL CO.,LTD.");
        manufacturers.put(776, "Surefire, LLC");
        manufacturers.put(777, "Dolby Labs");
        manufacturers.put(778, "Ellisys");
        manufacturers.put(779, "Magnitude Lighting Converters");
        manufacturers.put(780, "Hilti AG");
        manufacturers.put(781, "Devdata S.r.l.");
        manufacturers.put(782, "Deviceworx");
        manufacturers.put(783, "Shortcut Labs");
        manufacturers.put(784, "SGL Italia S.r.l.");
        manufacturers.put(785, "PEEQ DATA");
        manufacturers.put(786, "Ducere Technologies Pvt Ltd");
        manufacturers.put(787, "DiveNav, Inc.");
        manufacturers.put(788, "RIIG AI Sp. z o.o.");
        manufacturers.put(789, "Thermo Fisher Scientific");
        manufacturers.put(790, "AG Measurematics Pvt. Ltd.");
        manufacturers.put(791, "CHUO Electronics CO., LTD.");
        manufacturers.put(792, "Aspenta International");
        manufacturers.put(793, "Eugster Frismag AG");
        manufacturers.put(794, "Amber wireless GmbH");
        manufacturers.put(795, "HQ Inc");
        manufacturers.put(796, "Lab Sensor Solutions");
        manufacturers.put(797, "Enterlab ApS");
        manufacturers.put(798, "Eyefi, Inc.");
        manufacturers.put(799, "MetaSystem S.p.A.");
        manufacturers.put(800, "SONO ELECTRONICS. CO., LTD");
        manufacturers.put(801, "Jewelbots");
        manufacturers.put(802, "Compumedics Limited");
        manufacturers.put(803, "Rotor Bike Components");
        manufacturers.put(804, "Astro, Inc.");
        manufacturers.put(805, "Amotus Solutions");
        manufacturers.put(806, "Healthwear Technologies (Changzhou)Ltd");
        manufacturers.put(807, "Essex Electronics");
        manufacturers.put(808, "Grundfos A/S");
        manufacturers.put(809, "Eargo, Inc.");
        manufacturers.put(810, "Electronic Design Lab");
        manufacturers.put(811, "ESYLUX");
        manufacturers.put(812, "NIPPON SMT.CO.,Ltd");
        manufacturers.put(813, "BM innovations GmbH");
        manufacturers.put(814, "indoormap");
        manufacturers.put(815, "OttoQ Inc");
        manufacturers.put(816, "North Pole Engineering");
        manufacturers.put(817, "3flares Technologies Inc.");
        manufacturers.put(818, "Electrocompaniet A.S.");
        manufacturers.put(819, "Mul-T-Lock");
        manufacturers.put(820, "Corentium AS");
        manufacturers.put(821, "Enlighted Inc");
        manufacturers.put(822, "GISTIC");
        manufacturers.put(823, "AJP2 Holdings, LLC");
        manufacturers.put(824, "COBI GmbH");
        manufacturers.put(825, "Blue Sky Scientific, LLC");
        manufacturers.put(826, "Appception, Inc.");
        manufacturers.put(827, "Courtney Thorne Limited");
        manufacturers.put(828, "Virtuosys");
        manufacturers.put(829, "TPV Technology Limited");
        manufacturers.put(830, "Monitra SA");
        manufacturers.put(831, "Automation Components, Inc.");
        manufacturers.put(832, "Letsense s.r.l.");
        manufacturers.put(833, "Etesian Technologies LLC");
        manufacturers.put(834, "GERTEC BRASIL LTDA.");
        manufacturers.put(835, "Drekker Development Pty. Ltd.");
        manufacturers.put(836, "Whirl Inc");
        manufacturers.put(837, "Locus Positioning");
        manufacturers.put(838, "Acuity Brands Lighting, Inc");
        manufacturers.put(839, "Prevent Biometrics");
        manufacturers.put(840, "Arioneo");
        manufacturers.put(841, "VersaMe");
        manufacturers.put(842, "Vaddio");
        manufacturers.put(843, "Libratone A/S");
        manufacturers.put(844, "HM Electronics, Inc.");
        manufacturers.put(845, "TASER International, Inc.");
        manufacturers.put(846, "SafeTrust Inc.");
        manufacturers.put(847, "Heartland Payment Systems");
        manufacturers.put(848, "Bitstrata Systems Inc.");
        manufacturers.put(849, "Pieps GmbH");
        manufacturers.put(850, "iRiding(Xiamen)Technology Co.,Ltd.");
        manufacturers.put(851, "Alpha Audiotronics, Inc.");
        manufacturers.put(852, "TOPPAN FORMS CO.,LTD.");
        manufacturers.put(853, "Sigma Designs, Inc.");
        manufacturers.put(854, "Spectrum Brands, Inc.");
        manufacturers.put(855, "Polymap Wireless");
        manufacturers.put(856, "MagniWare Ltd.");
        manufacturers.put(857, "Novotec Medical GmbH");
        manufacturers.put(858, "Medicom Innovation Partner a/s");
        manufacturers.put(859, "Matrix Inc.");
        manufacturers.put(860, "Eaton Corporation");
        manufacturers.put(861, "KYS");
        manufacturers.put(862, "Naya Health, Inc.");
        manufacturers.put(863, "Acromag");
        manufacturers.put(864, "Insulet Corporation");
        manufacturers.put(865, "Wellinks Inc.");
        manufacturers.put(866, "ON Semiconductor");
        manufacturers.put(867, "FREELAP SA");
        manufacturers.put(868, "Favero Electronics Srl");
        manufacturers.put(869, "BioMech Sensor LLC");
        manufacturers.put(870, "BOLTT Sports technologies Private limited");
        manufacturers.put(871, "Saphe International");
        manufacturers.put(872, "Metormote AB");
        manufacturers.put(873, "littleBits");
        manufacturers.put(874, "SetPoint Medical");
        manufacturers.put(875, "BRControls Products BV");
        manufacturers.put(876, "Zipcar");
        manufacturers.put(877, "AirBolt Pty Ltd");
        manufacturers.put(878, "KeepTruckin Inc");
        manufacturers.put(879, "Motiv, Inc.");
        manufacturers.put(880, "Wazombi Labs O");
        manufacturers.put(881, "ORBCOMM");
        manufacturers.put(882, "Nixie Labs, Inc.");
        manufacturers.put(883, "AppNearMe Ltd");
        manufacturers.put(884, "Holman Industries");
        manufacturers.put(885, "Expain AS");
        manufacturers.put(886, "Electronic Temperature Instruments Ltd");
        manufacturers.put(887, "Plejd AB");
        manufacturers.put(888, "Propeller Health");
        manufacturers.put(889, "Shenzhen iMCO Electronic Technology Co.,Ltd");
        manufacturers.put(890, "Algoria");
        manufacturers.put(891, "Apption Labs Inc.");
        manufacturers.put(892, "Cronologics Corporation");
        manufacturers.put(893, "MICRODIA Ltd.");
        manufacturers.put(894, "lulabytes S.L.");
        manufacturers.put(895, "Nestec S.A.");
        manufacturers.put(896, "LLC \"MEGA-F service\"");
        manufacturers.put(897, "Sharp Corporation");
        manufacturers.put(898, "Precision Outcomes Ltd");
        manufacturers.put(899, "Kronos Incorporated");
        manufacturers.put(900, "OCOSMOS Co., Ltd.");
        manufacturers.put(901, "Embedded Electronic Solutions Ltd. dba e2Solutions");
        manufacturers.put(902, "Aterica Inc.");
        manufacturers.put(903, "BluStor PMC, Inc.");
        manufacturers.put(904, "Kapsch TrafficCom AB");
        manufacturers.put(905, "ActiveBlu Corporation");
        manufacturers.put(906, "Kohler Mira Limited");
        manufacturers.put(907, "Noke");
        manufacturers.put(908, "Appion Inc.");
        manufacturers.put(909, "Resmed Ltd");
        manufacturers.put(910, "Crownstone B.V.");
        manufacturers.put(911, "Xiaomi Inc.");
        manufacturers.put(912, "INFOTECH s.r.o.");
        manufacturers.put(913, "Thingsquare AB");
        manufacturers.put(914, "T&D");
        manufacturers.put(915, "LAVAZZA S.p.A.");
        manufacturers.put(916, "Netclearance Systems, Inc.");
        manufacturers.put(917, "SDATAWAY");
        manufacturers.put(918, "BLOKS GmbH");
        manufacturers.put(919, "LEGO System A/S");
        manufacturers.put(920, "Thetatronics Ltd");
        manufacturers.put(921, "Nikon Corporation");
        manufacturers.put(922, "NeST");
        manufacturers.put(923, "South Silicon Valley Microelectronics");
        manufacturers.put(924, "ALE International");
        manufacturers.put(925, "CareView Communications, Inc.");
        manufacturers.put(926, "SchoolBoard Limited");
        manufacturers.put(927, "Molex Corporation");
        manufacturers.put(928, "IVT Wireless Limited");
        manufacturers.put(929, "Alpine Labs LLC");
        manufacturers.put(930, "Candura Instruments");
        manufacturers.put(931, "SmartMovt Technology Co., Ltd");
        manufacturers.put(932, "Token Zero Ltd");
        manufacturers.put(933, "ACE CAD Enterprise Co., Ltd. (ACECAD)");
        manufacturers.put(934, "Medela, Inc");
        manufacturers.put(935, "AeroScout");
        manufacturers.put(936, "Esrille Inc.");
        manufacturers.put(937, "THINKERLY SRL");
        manufacturers.put(938, "Exon Sp. z o.o.");
        manufacturers.put(939, "Meizu Technology Co., Ltd.");
        manufacturers.put(940, "Smablo LTD");
        manufacturers.put(941, "XiQ");
        manufacturers.put(942, "Allswell Inc.");
        manufacturers.put(943, "Comm-N-Sense Corp DBA Verigo");
        manufacturers.put(944, "VIBRADORM GmbH");
        manufacturers.put(945, "Otodata Wireless Network Inc.");
        manufacturers.put(946, "Propagation Systems Limited");
        manufacturers.put(947, "Midwest Instruments & Controls");
        manufacturers.put(948, "Alpha Nodus, inc.");
        manufacturers.put(949, "petPOMM, Inc");
        manufacturers.put(950, "Mattel");
        manufacturers.put(951, "Airbly Inc.");
        manufacturers.put(952, "A-Safe Limited");
        manufacturers.put(953, "FREDERIQUE CONSTANT SA");
        manufacturers.put(954, "Maxscend Microelectronics Company Limited");
        manufacturers.put(955, "Abbott Diabetes Care");
        manufacturers.put(956, "ASB Bank Ltd");
        manufacturers.put(957, "amadas");
        manufacturers.put(958, "Applied Science, Inc.");
        manufacturers.put(959, "iLumi Solutions Inc.");
        manufacturers.put(960, "Arch Systems Inc.");
        manufacturers.put(961, "Ember Technologies, Inc.");
        manufacturers.put(962, "Snapchat Inc");
        manufacturers.put(963, "Casambi Technologies Oy");
        manufacturers.put(964, "Pico Technology Inc.");
        manufacturers.put(965, "St. Jude Medical, Inc.");
        manufacturers.put(966, "Intricon");
        manufacturers.put(967, "Structural Health Systems, Inc.");
        manufacturers.put(968, "Avvel International");
        manufacturers.put(969, "Gallagher Group");
        manufacturers.put(970, "In2things Automation Pvt. Ltd.");
        manufacturers.put(971, "SYSDEV Srl");
        manufacturers.put(972, "Vonkil Technologies Ltd");
        manufacturers.put(973, "Wynd Technologies, Inc.");
        manufacturers.put(974, "CONTRINEX S.A.");
        manufacturers.put(975, "MIRA, Inc.");
        manufacturers.put(976, "Watteam Ltd");
        manufacturers.put(977, "Density Inc.");
        manufacturers.put(978, "IOT Pot India Private Limited");
        manufacturers.put(979, "Sigma Connectivity AB");
        manufacturers.put(980, "PEG PEREGO SPA");
        manufacturers.put(981, "Wyzelink Systems Inc.");
        manufacturers.put(982, "Yota Devices LTD");
        manufacturers.put(983, "FINSECUR");
        manufacturers.put(984, "Zen-Me Labs Ltd");
        manufacturers.put(985, "3IWare Co., Ltd.");
        manufacturers.put(986, "EnOcean GmbH");
        manufacturers.put(987, "Instabeat, Inc");
        manufacturers.put(988, "Nima Labs");
        manufacturers.put(989, "Andreas Stihl AG & Co. KG");
        manufacturers.put(990, "Nathan Rhoades LLC");
        manufacturers.put(991, "Grob Technologies, LLC");
        manufacturers.put(992, "Actions (Zhuhai) Technology Co., Limited");
        manufacturers.put(993, "SPD Development Company Ltd");
        manufacturers.put(994, "Sensoan Oy");
        manufacturers.put(995, "Qualcomm Life Inc");
        manufacturers.put(996, "Chip-ing AG");
        manufacturers.put(997, "ffly4u");
        manufacturers.put(998, "IoT Instruments Oy");
        manufacturers.put(999, "TRUE Fitness Technology");
        manufacturers.put(1000, "Reiner Kartengeraete GmbH & Co. KG.");
        manufacturers.put(1001, "SHENZHEN LEMONJOY TECHNOLOGY CO., LTD.");
        manufacturers.put(1002, "Hello Inc.");
        manufacturers.put(1003, "Evollve Inc.");
        manufacturers.put(1004, "Jigowatts Inc.");
        manufacturers.put(1005, "BASIC MICRO.COM,INC.");
        manufacturers.put(1006, "CUBE TECHNOLOGIES");
        manufacturers.put(1007, "foolography GmbH");
        manufacturers.put(1008, "CLINK");
        manufacturers.put(1009, "Hestan Smart Cooking Inc.");
        manufacturers.put(1010, "WindowMaster A/S");
        manufacturers.put(1011, "Flowscape AB");
        manufacturers.put(1012, "PAL Technologies Ltd");
        manufacturers.put(1013, "WHERE, Inc.");
        manufacturers.put(1014, "Iton Technology Corp.");
        manufacturers.put(1015, "Owl Labs Inc.");
        manufacturers.put(1016, "Rockford Corp.");
        manufacturers.put(1017, "Becon Technologies Co.,Ltd.");
        manufacturers.put(1018, "Vyassoft Technologies Inc");
        manufacturers.put(1019, "Nox Medical");
        manufacturers.put(1020, "Kimberly-Clark");
        manufacturers.put(1021, "Trimble Navigation Ltd.");
        manufacturers.put(1022, "Littelfuse");
        manufacturers.put(1023, "Withings");
        manufacturers.put(1024, "i-developer IT Beratung UG");
        manufacturers.put(1025, "");
        manufacturers.put(1026, "Sears Holdings Corporation");
        manufacturers.put(1027, "Gantner Electronic GmbH");
        manufacturers.put(1028, "Authomate Inc");
        manufacturers.put(1029, "Vertex International, Inc.");
        manufacturers.put(1030, "Airtago");
        manufacturers.put(1031, "Swiss Audio SA");
        manufacturers.put(1032, "ToGetHome Inc.");
        manufacturers.put(1033, "AXIS");
        manufacturers.put(1034, "Openmatics");
        manufacturers.put(1035, "Jana Care Inc.");
        manufacturers.put(1036, "Senix Corporation");
        manufacturers.put(1037, "NorthStar Battery Company, LLC");
        manufacturers.put(1038, "SKF (U.K.) Limited");
        manufacturers.put(1039, "CO-AX Technology, Inc.");
        manufacturers.put(1040, "Fender Musical Instruments");
        manufacturers.put(1041, "Luidia Inc");
        manufacturers.put(1042, "SEFAM");
        manufacturers.put(1043, "Wireless Cables Inc");
        manufacturers.put(1044, "Lightning Protection International Pty Ltd");
        manufacturers.put(1045, "Uber Technologies Inc");
        manufacturers.put(1046, "SODA GmbH");
        manufacturers.put(1047, "Fatigue Science");
        manufacturers.put(1048, "Alpine Electronics Inc.");
        manufacturers.put(1049, "Novalogy LTD");
        manufacturers.put(1050, "Friday Labs Limited");
        manufacturers.put(1051, "OrthoAccel Technologies");
        manufacturers.put(1052, "WaterGuru, Inc.");
        manufacturers.put(1053, "Benning Elektrotechnik und Elektronik GmbH & Co. KG");
        manufacturers.put(1054, "Dell Computer Corporation");
        manufacturers.put(1055, "Kopin Corporation");
        manufacturers.put(1056, "TecBakery GmbH");
        manufacturers.put(1057, "Backbone Labs, Inc.");
        manufacturers.put(1058, "DELSEY SA");
        manufacturers.put(1059, "Chargifi Limited");
        manufacturers.put(1060, "Trainesense Ltd.");
        manufacturers.put(1061, "Unify Software and Solutions GmbH & Co. KG");
        manufacturers.put(1062, "Husqvarna AB");
        manufacturers.put(1063, "Focus fleet and fuel management inc");
        manufacturers.put(1064, "SmallLoop, LLC");
        manufacturers.put(1065, "Prolon Inc.");
        manufacturers.put(1066, "BD Medical");
        manufacturers.put(1067, "iMicroMed Incorporated");
        manufacturers.put(1068, "Ticto N.V.");
        manufacturers.put(1069, "Meshtech AS");
        manufacturers.put(1070, "MemCachier Inc.");
        manufacturers.put(1071, "Danfoss A/S");
        manufacturers.put(1072, "SnapStyk Inc.");
        manufacturers.put(1073, "Amway Corporation");
        manufacturers.put(1074, "Silk Labs, Inc.");
        manufacturers.put(1075, "Pillsy Inc.");
        manufacturers.put(1076, "Hatch Baby, Inc.");
        manufacturers.put(1077, "Blocks Wearables Ltd.");
        manufacturers.put(1078, "Drayson Technologies (Europe) Limited");
        manufacturers.put(1079, "eBest IOT Inc.");
        manufacturers.put(1080, "Helvar Ltd");
        manufacturers.put(1081, "Radiance Technologies");
        manufacturers.put(1082, "Nuheara Limited");
        manufacturers.put(1083, "Appside co., ltd.");
        manufacturers.put(1084, "DeLaval");
        manufacturers.put(1085, "Coiler Corporation");
        manufacturers.put(1086, "Thermomedics, Inc.");
        manufacturers.put(1087, "Tentacle Sync GmbH");
        manufacturers.put(1088, "Valencell, Inc.");
        manufacturers.put(1089, "iProtoXi Oy");
        manufacturers.put(1090, "SECOM CO., LTD.");
        manufacturers.put(1091, "Tucker International LLC");
        manufacturers.put(1092, "Metanate Limited");
        manufacturers.put(1093, "Kobian Canada Inc.");
        manufacturers.put(1094, "NETGEAR, Inc.");
        manufacturers.put(1095, "Fabtronics Australia Pty Ltd");
        manufacturers.put(1096, "Grand Centrix GmbH");
        manufacturers.put(1097, "1UP USA.com llc");
        manufacturers.put(1098, "SHIMANO INC.");
        manufacturers.put(1099, "Nain Inc.");
        manufacturers.put(1100, "LifeStyle Lock, LLC");
        manufacturers.put(1101, "VEGA Grieshaber KG");
        manufacturers.put(1102, "Xtrava Inc.");
        manufacturers.put(1103, "TTS Tooltechnic Systems AG & Co. KG");
        manufacturers.put(1104, "Teenage Engineering AB");
        manufacturers.put(1105, "Tunstall Nordic AB");
        manufacturers.put(1106, "Svep Design Center AB");
        manufacturers.put(1107, "GreenPeak Technologies BV");
        manufacturers.put(1108, "Sphinx Electronics GmbH & Co KG");
        manufacturers.put(1109, "Atomation");
        manufacturers.put(1110, "Nemik Consulting Inc");
        manufacturers.put(1111, "RF INNOVATION");
        manufacturers.put(1112, "Mini Solution Co., Ltd.");
        manufacturers.put(1113, "Lumenetix, Inc");
        manufacturers.put(1114, "2048450 Ontario Inc");
        manufacturers.put(1115, "SPACEEK LTD");
        manufacturers.put(1116, "Delta T Corporation");
        manufacturers.put(1117, "Boston Scientific Corporation");
        manufacturers.put(1118, "Nuviz, Inc.");
        manufacturers.put(1119, "Real Time Automation, Inc.");
        manufacturers.put(1120, "Kolibree");
        manufacturers.put(1121, "vhf elektronik GmbH");
        manufacturers.put(1122, "Bonsai Systems GmbH");
        manufacturers.put(1123, "Fathom Systems Inc.");
        manufacturers.put(1124, "Bellman & Symfon");
        manufacturers.put(1125, "International Forte Group LLC");
        manufacturers.put(1126, "CycleLabs Solutions inc.");
        manufacturers.put(1127, "Codenex Oy");
        manufacturers.put(1128, "Kynesim Ltd");
        manufacturers.put(1129, "Palago AB");
        manufacturers.put(1130, "INSIGMA INC.");
        manufacturers.put(1131, "PMD Solutions");
        manufacturers.put(1132, "Qingdao Realtime Technology Co., Ltd.");
        manufacturers.put(1133, "BEGA Gantenbrink-Leuchten KG");
        manufacturers.put(1134, "Pambor Ltd.");
        manufacturers.put(1135, "Develco Products A/S");
        manufacturers.put(1136, "iDesign s.r.l.");
        manufacturers.put(1137, "TiVo Corp");
        manufacturers.put(1138, "Control-J Pty Ltd");
        manufacturers.put(1139, "Steelcase, Inc.");
        manufacturers.put(1140, "iApartment co., ltd.");
        manufacturers.put(1141, "Icom inc.");
        manufacturers.put(1142, "Oxstren Wearable Technologies Private Limited");
        manufacturers.put(1143, "Blue Spark Technologies");
        manufacturers.put(1144, "FarSite Communications Limited");
        manufacturers.put(1145, "mywerk system GmbH");
        manufacturers.put(1146, "Sinosun Technology Co., Ltd.");
        manufacturers.put(1147, "MIYOSHI ELECTRONICS CORPORATION");
        manufacturers.put(1148, "POWERMAT LTD");
        manufacturers.put(1149, "Occly LLC");
        manufacturers.put(1150, "OurHub Dev IvS");
        manufacturers.put(1151, "Pro-Mark, Inc.");
        manufacturers.put(1152, "Dynometrics Inc.");
        manufacturers.put(1153, "Quintrax Limited");
        manufacturers.put(1154, "POS Tuning Udo Vosshenrich GmbH & Co. KG");
        manufacturers.put(1155, "Multi Care Systems B.V.");
        manufacturers.put(1156, "Revol Technologies Inc");
        manufacturers.put(1157, "SKIDATA AG");
        manufacturers.put(1158, "DEV TECNOLOGIA INDUSTRIA, COMERCIO E MANUTENCAO DE EQUIPAMENTOS LTDA. - ME");
        manufacturers.put(1159, "Centrica Connected Home");
        manufacturers.put(1160, "Automotive Data Solutions Inc");
        manufacturers.put(1161, "Igarashi Engineering");
        manufacturers.put(1162, "Taelek Oy");
        manufacturers.put(1163, "CP Electronics Limited");
        manufacturers.put(1164, "Vectronix AG");
        manufacturers.put(1165, "S-Labs Sp. z o.o.");
        manufacturers.put(1166, "Companion Medical, Inc.");
        manufacturers.put(1167, "BlueKitchen GmbH");
        manufacturers.put(1168, "Matting AB");
        manufacturers.put(1169, "SOREX - Wireless Solutions GmbH");
        manufacturers.put(1170, "ADC Technology, Inc.");
        manufacturers.put(1171, "Lynxemi Pte Ltd");
        manufacturers.put(1172, "SENNHEISER electronic GmbH & Co. KG");
        manufacturers.put(1173, "LMT Mercer Group, Inc");
        manufacturers.put(1174, "Polymorphic Labs LLC");
        manufacturers.put(1175, "Cochlear Limited");
        manufacturers.put(1176, "METER Group, Inc. USA");
        manufacturers.put(1177, "Ruuvi Innovations Ltd.");
        manufacturers.put(1178, "Situne AS");
        manufacturers.put(1179, "nVisti, LLC");
        manufacturers.put(1180, "DyOcean");
        manufacturers.put(1181, "Uhlmann & Zacher GmbH");
        manufacturers.put(1182, "AND!XOR LLC");
        manufacturers.put(1183, "tictote AB");
        manufacturers.put(1184, "Vypin, LLC");
        manufacturers.put(1185, "PNI Sensor Corporation");
        manufacturers.put(1186, "ovrEngineered, LLC");
        manufacturers.put(1187, "GT-tronics HK Ltd");
        manufacturers.put(1188, "Herbert Waldmann GmbH & Co. KG");
        manufacturers.put(1189, "Guangzhou FiiO Electronics Technology Co.,Ltd");
        manufacturers.put(1190, "Vinetech Co., Ltd");
        manufacturers.put(1191, "Dallas Logic Corporation");
        manufacturers.put(1192, "BioTex, Inc.");
        manufacturers.put(1193, "DISCOVERY SOUND TECHNOLOGY, LLC");
        manufacturers.put(1194, "LINKIO SAS");
        manufacturers.put(1195, "Harbortronics, Inc.");
        manufacturers.put(1196, "Undagrid B.V.");
        manufacturers.put(1197, "Shure Inc");
        manufacturers.put(1198, "ERM Electronic Systems LTD");
        manufacturers.put(1199, "BIOROWER Handelsagentur GmbH");
        manufacturers.put(1200, "Weba Sport und Med. Artikel GmbH");
        manufacturers.put(1201, "Kartographers Technologies Pvt. Ltd.");
        manufacturers.put(1202, "The Shadow on the Moon");
        manufacturers.put(1203, "mobike (Hong Kong) Limited");
        manufacturers.put(1204, "Inuheat Group AB");
        manufacturers.put(1205, "Swiftronix AB");
        manufacturers.put(1206, "Diagnoptics Technologies");
        manufacturers.put(1207, "Analog Devices, Inc.");
        manufacturers.put(1208, "Soraa Inc.");
        manufacturers.put(1209, "CSR Building Products Limited");
        manufacturers.put(1210, "Crestron Electronics, Inc.");
        manufacturers.put(1211, "Neatebox Ltd");
        manufacturers.put(1212, "Draegerwerk AG & Co. KGaA");
        manufacturers.put(1213, "AlbynMedical");
        manufacturers.put(1214, "Averos FZCO");
        manufacturers.put(1215, "VIT Initiative, LLC");
        manufacturers.put(1216, "Statsports International");
        manufacturers.put(1217, "Sospitas, s.r.o.");
        manufacturers.put(1218, "Dmet Products Corp.");
        manufacturers.put(1219, "Mantracourt Electronics Limited");
        manufacturers.put(1220, "TeAM Hutchins AB");
        manufacturers.put(1221, "Seibert Williams Glass, LLC");
        manufacturers.put(1222, "Insta GmbH");
        manufacturers.put(1223, "Svantek Sp. z o.o.");
        manufacturers.put(1224, "Shanghai Flyco Electrical Appliance Co., Ltd.");
        manufacturers.put(1225, "Thornwave Labs Inc");
        manufacturers.put(1226, "Steiner-Optik GmbH");
        manufacturers.put(1227, "Novo Nordisk A/S");
        manufacturers.put(1228, "Enflux Inc.");
        manufacturers.put(1229, "Safetech Products LLC");
        manufacturers.put(1230, "GOOOLED S.R.L.");
        manufacturers.put(1231, "DOM Sicherheitstechnik GmbH & Co. KG");
        manufacturers.put(1232, "Olympus Corporation");
        manufacturers.put(1233, "KTS GmbH");
        manufacturers.put(1234, "Anloq Technologies Inc.");
        manufacturers.put(1235, "Queercon, Inc");
        manufacturers.put(1236, "5th Element Ltd");
        manufacturers.put(1237, "Gooee Limited");
        manufacturers.put(1238, "LUGLOC LLC");
        manufacturers.put(1239, "Blincam, Inc.");
        manufacturers.put(1240, "FUJIFILM Corporation");
        manufacturers.put(1241, "RandMcNally");
        manufacturers.put(1242, "Franceschi Marina snc");
        manufacturers.put(1243, "Engineered Audio, LLC.");
        manufacturers.put(1244, "IOTTIVE (OPC) PRIVATE LIMITED");
        manufacturers.put(1245, "4MOD Technology");
        manufacturers.put(1246, "Lutron Electronics Co., Inc.");
        manufacturers.put(1247, "Emerson");
        manufacturers.put(1248, "Guardtec, Inc.");
        manufacturers.put(1249, "REACTEC LIMITED");
        manufacturers.put(1250, "EllieGrid");
        manufacturers.put(1251, "Under Armour");
        manufacturers.put(1252, "Woodenshark");
        manufacturers.put(1253, "Avack Oy");
        manufacturers.put(1254, "Smart Solution Technology, Inc.");
        manufacturers.put(1255, "REHABTRONICS INC.");
        manufacturers.put(1256, "STABILO International");
        manufacturers.put(1257, "Busch Jaeger Elektro GmbH");
        manufacturers.put(1258, "Pacific Bioscience Laboratories, Inc");
        manufacturers.put(1259, "Bird Home Automation GmbH");
        manufacturers.put(1260, "Motorola Solutions");
        manufacturers.put(1261, "R9 Technology, Inc.");
        manufacturers.put(1262, "Auxivia");
        manufacturers.put(1263, "DaisyWorks, Inc");
        manufacturers.put(1264, "Kosi Limited");
        manufacturers.put(1265, "Theben AG");
        manufacturers.put(1266, "InDreamer Techsol Private Limited");
        manufacturers.put(1267, "Cerevast Medical");
        manufacturers.put(1268, "ZanCompute Inc.");
        manufacturers.put(1269, "Pirelli Tyre S.P.A.");
        manufacturers.put(1270, "McLear Limited");
        manufacturers.put(1271, "Shenzhen Huiding Technology Co.,Ltd.");
        manufacturers.put(1272, "Convergence Systems Limited");
        manufacturers.put(1273, "Interactio");
        manufacturers.put(1274, "Androtec GmbH");
        manufacturers.put(1275, "Benchmark Drives GmbH & Co. KG");
        manufacturers.put(1276, "SwingLync L. L. C.");
        manufacturers.put(1277, "Tapkey GmbH");
        manufacturers.put(1278, "Woosim Systems Inc.");
    }

    public static String getManufacturer(int id) {
        return manufacturers.get(id);
    }
}
