/*
* generated by Xtext
*/
package org.eclipse.smarthome.model.notification;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class NotificationStandaloneSetup extends NotificationStandaloneSetupGenerated{

	public static void doSetup() {
		new NotificationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

