/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.notification;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NotificationRuntimeModule extends org.eclipse.smarthome.model.notification.AbstractNotificationRuntimeModule {

}
