/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.ui.contentassist

import org.eclipse.smarthome.model.ui.contentassist.AbstractSitemapProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SitemapProposalProvider extends AbstractSitemapProposalProvider {
}
