/**
 * Copyright (c) 2014-2016 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.persistence.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PersistenceUiModule extends org.eclipse.smarthome.model.persistence.ui.AbstractPersistenceUiModule {
    public PersistenceUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
