/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.notification.ui.contentassist

import org.eclipse.smarthome.model.notification.ui.contentassist.AbstractNotificationProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class NotificationProposalProvider extends AbstractNotificationProposalProvider {
}
