/*
 * Copyright (c) Alexander Kammerer 2015.
 *
 * All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 11:55:42 PM CEST 
//

package org.eclipse.smarthome.documentation.schemas.binding.v1_0;

import org.eclipse.smarthome.documentation.schemas.config_description.v1_0.ConfigDescription;
import org.eclipse.smarthome.documentation.schemas.config_description.v1_0.ConfigDescriptionRef;

import javax.xml.bind.annotation.*;

/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="config-description" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}configDescription"/>
 *           &lt;element name="config-description-ref" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}configDescriptionRef"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}idRestrictionPattern" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "", propOrder = { "name", "description", "author",
        "configDescription", "configDescriptionRef" }) @XmlRootElement(name = "binding") public class Binding {

    @XmlElement(required = true) protected String name;
    protected String description;
    @XmlElement(required = true) protected String author;
    @XmlElement(name = "config-description") protected ConfigDescription configDescription;
    @XmlElement(name = "config-description-ref") protected ConfigDescriptionRef configDescriptionRef;
    @XmlAttribute(name = "id", required = true) protected String id;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the author property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the configDescription property.
     *
     * @return possible object is
     * {@link ConfigDescription }
     */
    public ConfigDescription getConfigDescription() {
        return configDescription;
    }

    /**
     * Sets the value of the configDescription property.
     *
     * @param value allowed object is
     *              {@link ConfigDescription }
     */
    public void setConfigDescription(ConfigDescription value) {
        this.configDescription = value;
    }

    /**
     * Gets the value of the configDescriptionRef property.
     *
     * @return possible object is
     * {@link ConfigDescriptionRef }
     */
    public ConfigDescriptionRef getConfigDescriptionRef() {
        return configDescriptionRef;
    }

    /**
     * Sets the value of the configDescriptionRef property.
     *
     * @param value allowed object is
     *              {@link ConfigDescriptionRef }
     */
    public void setConfigDescriptionRef(ConfigDescriptionRef value) {
        this.configDescriptionRef = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

}
