/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.smarthome.model.rule.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class RulesScopeProvider extends AbstractRulesScopeProvider {

}
