/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.notification.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NotificationUiModule extends org.eclipse.smarthome.model.notification.ui.AbstractNotificationUiModule {
	public NotificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
