/*
 * generated by Xtext
 */
package org.eclipse.smarthome.model.thing.ui.contentassist

import org.eclipse.smarthome.model.thing.ui.contentassist.AbstractThingProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ThingProposalProvider extends AbstractThingProposalProvider {
}
