
/*
 * Copyright (c) Alexander Kammerer 2015.
 *
 * All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 07:48:00 PM CEST 
//


package org.eclipse.smarthome.documentation.schemas.config_description.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.eclipse.smarthome.schemas.config_description.v1_0 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConfigDescription_QNAME = new QName("http://eclipse.org/smarthome/schemas/config-description/v1.0.0", "config-description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.eclipse.smarthome.schemas.config_description.v1_0
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FilterType }
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link OptionsType }
     */
    public OptionsType createOptionsType() {
        return new OptionsType();
    }

    /**
     * Create an instance of {@link ConfigDescriptions }
     */
    public ConfigDescriptions createConfigDescriptions() {
        return new ConfigDescriptions();
    }

    /**
     * Create an instance of {@link ConfigDescription }
     */
    public ConfigDescription createConfigDescription() {
        return new ConfigDescription();
    }

    /**
     * Create an instance of {@link Parameter }
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ParameterGroup }
     */
    public ParameterGroup createParameterGroup() {
        return new ParameterGroup();
    }

    /**
     * Create an instance of {@link ConfigDescriptionRef }
     */
    public ConfigDescriptionRef createConfigDescriptionRef() {
        return new ConfigDescriptionRef();
    }

    /**
     * Create an instance of {@link FilterType.Criteria }
     */
    public FilterType.Criteria createFilterTypeCriteria() {
        return new FilterType.Criteria();
    }

    /**
     * Create an instance of {@link OptionsType.Option }
     */
    public OptionsType.Option createOptionsTypeOption() {
        return new OptionsType.Option();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigDescription }{@code >}}
     */
    @XmlElementDecl(namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0", name = "config-description")
    public JAXBElement<ConfigDescription> createConfigDescription(ConfigDescription value) {
        return new JAXBElement<ConfigDescription>(_ConfigDescription_QNAME, ConfigDescription.class, null, value);
    }

}
