/*
 * Copyright (c) Alexander Kammerer 2015.
 *
 * All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 07:48:00 PM CEST 
//

package org.eclipse.smarthome.documentation.schemas.config_description.v1_0;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * <p>Java class for parameter complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="parameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="context" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="default" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="options" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}optionsType" minOccurs="0"/>
 *         &lt;element name="limitToOptions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="filter" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}filterType" minOccurs="0"/>
 *         &lt;element name="advanced" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="multipleLimit" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://eclipse.org/smarthome/schemas/config-description/v1.0.0}parameterType" />
 *       &lt;attribute name="groupName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="readOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="multiple" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "parameter", propOrder = {

}) public class Parameter {

    protected String context;
    @XmlElement(defaultValue = "false") protected Boolean required;
    @XmlElement(name = "default") protected String _default;
    protected String label;
    protected String description;
    protected OptionsType options;
    protected Boolean limitToOptions;
    protected FilterType filter;
    protected Boolean advanced;
    protected BigInteger multipleLimit;
    @XmlAttribute(name = "name", required = true) protected String name;
    @XmlAttribute(name = "type", required = true) protected ParameterType type;
    @XmlAttribute(name = "groupName") protected String groupName;
    @XmlAttribute(name = "min") protected BigDecimal min;
    @XmlAttribute(name = "max") protected BigDecimal max;
    @XmlAttribute(name = "step") protected BigDecimal step;
    @XmlAttribute(name = "pattern") protected String pattern;
    @XmlAttribute(name = "required") protected Boolean valueToFixError2;
    @XmlAttribute(name = "readOnly") protected Boolean readOnly;
    @XmlAttribute(name = "multiple") protected Boolean multiple;

    /**
     * Gets the value of the context property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContext(String value) {
        this.context = value;
    }

    /**
     * Gets the value of the required property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the default property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefault(String value) {
        this._default = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the options property.
     *
     * @return possible object is
     * {@link OptionsType }
     */
    public OptionsType getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     *
     * @param value allowed object is
     *              {@link OptionsType }
     */
    public void setOptions(OptionsType value) {
        this.options = value;
    }

    /**
     * Gets the value of the limitToOptions property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isLimitToOptions() {
        return limitToOptions;
    }

    /**
     * Sets the value of the limitToOptions property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setLimitToOptions(Boolean value) {
        this.limitToOptions = value;
    }

    /**
     * Gets the value of the filter property.
     *
     * @return possible object is
     * {@link FilterType }
     */
    public FilterType getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     *
     * @param value allowed object is
     *              {@link FilterType }
     */
    public void setFilter(FilterType value) {
        this.filter = value;
    }

    /**
     * Gets the value of the advanced property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isAdvanced() {
        return advanced;
    }

    /**
     * Sets the value of the advanced property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setAdvanced(Boolean value) {
        this.advanced = value;
    }

    /**
     * Gets the value of the multipleLimit property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMultipleLimit() {
        return multipleLimit;
    }

    /**
     * Sets the value of the multipleLimit property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMultipleLimit(BigInteger value) {
        this.multipleLimit = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link ParameterType }
     */
    public ParameterType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link ParameterType }
     */
    public void setType(ParameterType value) {
        this.type = value;
    }

    /**
     * Gets the value of the groupName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the min property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMin(BigDecimal value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMax(BigDecimal value) {
        this.max = value;
    }

    /**
     * Gets the value of the step property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setStep(BigDecimal value) {
        this.step = value;
    }

    /**
     * Gets the value of the pattern property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the valueToFixError2 property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isValueToFixError2() {
        return valueToFixError2;
    }

    /**
     * Sets the value of the valueToFixError2 property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setValueToFixError2(Boolean value) {
        this.valueToFixError2 = value;
    }

    /**
     * Gets the value of the readOnly property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isReadOnly() {
        return readOnly;
    }

    /**
     * Sets the value of the readOnly property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadOnly(Boolean value) {
        this.readOnly = value;
    }

    /**
     * Gets the value of the multiple property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isMultiple() {
        return multiple;
    }

    /**
     * Sets the value of the multiple property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setMultiple(Boolean value) {
        this.multiple = value;
    }

}
